import type { Module } from "@/lib/types";

const level4BonusModules: Module[] = [
  {
    id: "l4-bonus-m1",
    title: "The HeLa Legacy",
    description: "Where science, consent, and justice collide — the story Henry has been waiting to tell",
    realm: 4,
    color: "#c0a0ff",
    nodes: [
      {
        id: "l4-bonus-m1-n1",
        moduleId: "l4-bonus-m1",
        title: "Henrietta Lacks & HeLa Cells",
        description: "The immortal cells that changed medicine — and the woman they came from",
        icon: "🧬",
        xpReward: 140,
        exercises: [
          {
            id: "l4-bonus-m1-n1-e1",
            type: "multiple-choice",
            question: "What does 'HeLa' stand for?",
            options: [
              "Helen Lawrence — a lab assistant at Johns Hopkins",
              "Henrietta Lacks — the patient whose cells were taken",
              "Henry Lacy — the scientist who discovered them",
              "Helena Laboratories — where they were first cultured",
            ],
            correctIndex: 1,
            hint: "⚗️ Henry steps forward. His image flickers. 'I want to tell you something,' he says quietly. 'Something I've been waiting a long time to say.'\n\nHeLa cells — named after Henrietta Lacks — were the first human cells to survive and thrive outside the human body, in 1951. They've been used in over 70,000 research papers. Without them, the polio vaccine might not exist. But Henrietta Lacks never consented to their use, and her family wasn't told for decades.\n\nDr. Henry Lacks chose THIS to be your final lesson.",
            explanation: "HeLa cells were named after Henrietta Lacks, a Black woman from Virginia whose cancer cells were taken in 1951 by Dr. George Gey at Johns Hopkins — without her knowledge or consent. The name encodes her identity, but the world didn't know that identity for decades.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e2",
            type: "multiple-choice",
            question: "What made HeLa cells scientifically revolutionary when they were first cultured in 1951?",
            options: [
              "They were genetically modified to be more durable",
              "They were the first human cells that could survive and replicate indefinitely outside the human body",
              "They were cloned from multiple donors to ensure genetic diversity",
              "They were immune to all known viruses",
            ],
            correctIndex: 1,
            explanation: "Before HeLa, human cells couldn't survive more than a few days in lab culture. HeLa cells divided relentlessly — scientists called them 'immortal.' This opened the door to decades of biological research that required living human cells.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e3",
            type: "multiple-choice",
            question: "Which major medical breakthrough was directly enabled by HeLa cells?",
            options: [
              "The discovery of DNA's double helix structure",
              "The development of the polio vaccine by Jonas Salk",
              "The first successful organ transplant",
              "The sequencing of the human genome",
            ],
            correctIndex: 1,
            explanation: "Jonas Salk used HeLa cells to test his polio vaccine in the 1950s. Without HeLa cells providing a reliable way to grow and test the virus, the vaccine might have taken far longer to develop. Henrietta Lacks' cells helped end polio — though she never knew it.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e4",
            type: "multiple-choice",
            question: "Approximately how many research publications have used HeLa cells, as of recent estimates?",
            options: [
              "About 500",
              "About 5,000",
              "Over 70,000",
              "Over 1 million",
            ],
            correctIndex: 2,
            explanation: "HeLa cells appear in over 70,000 scientific papers — on everything from cancer biology to virology to space radiation research (NASA sent them to space). They remain one of the most widely used biological tools in the history of science.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e5",
            type: "multiple-choice",
            question: "Why was Henrietta Lacks' identity kept secret for over 20 years after HeLa cells became famous?",
            options: [
              "She requested anonymity before she died",
              "Privacy norms of the era allowed hospitals to withhold patient identities — and institutional indifference to a Black woman's story did the rest",
              "Scientists genuinely didn't know whose cells they were using",
              "The cells were commercialized under a different name to avoid patent disputes",
            ],
            correctIndex: 1,
            explanation: "For decades, scientists published HeLa research without disclosing who the cells came from. When journalist Rebecca Skloot investigated in the 2000s, she uncovered a story of race, medicine, and power. Henrietta's identity had been obscured by a combination of era norms, racism, and institutional indifference — not any single deliberate act.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e6",
            type: "multiple-choice",
            question: "When were Henrietta Lacks' family members first told that her cells were alive and being used in research?",
            options: [
              "Immediately after her death in 1951",
              "When the cells were first commercialized in the 1960s",
              "In the early 1970s — over 20 years after her death",
              "They were officially notified in 2013 when the NIH sequenced the HeLa genome",
            ],
            correctIndex: 2,
            explanation: "The Lacks family found out in the early 1970s when a researcher contacted them for genetic samples. They had no idea HeLa cells existed, that the cells had been commercialized, or that laboratories worldwide were profiting from Henrietta's biology. The shock was profound.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n1-e7",
            type: "multiple-choice",
            question: "In 2013, the NIH sequenced the HeLa genome without the family's consent. What was the outcome?",
            options: [
              "The sequence was kept classified and never used",
              "After public outcry, the NIH reached an agreement with the Lacks family giving them a say in how genome data is accessed and shared",
              "The Lacks family sued and the genome data was legally destroyed",
              "The sequence was made fully public and remains completely uncontrolled",
            ],
            correctIndex: 1,
            hint: "⚗️ 'Progress without permission is still a form of taking,' Henry says quietly. 'The ethical story of HeLa didn't end in 1951. It's still unfolding.'",
            explanation: "The 2013 NIH-Lacks family agreement was a landmark: it created a data access committee including family members to review requests for HeLa genomic data. It was a partial — and long overdue — recognition that the Lacks family deserved a voice in how Henrietta's biology was used.",
            xpReward: 20,
          },
        ],
      },
      {
        id: "l4-bonus-m1-n2",
        moduleId: "l4-bonus-m1",
        title: "Informed Consent in Research",
        description: "The legal, ethical, and human dimensions of permission in science",
        icon: "📋",
        xpReward: 140,
        exercises: [
          {
            id: "l4-bonus-m1-n2-e1",
            type: "multiple-choice",
            question: "Informed consent in medical research requires that participants must:",
            options: [
              "Simply sign a form before the study begins",
              "Voluntarily agree after receiving full information about risks, benefits, alternatives, and their right to withdraw at any time",
              "Be compensated financially for their participation",
              "Be individually approved by a government agency before enrolling",
            ],
            correctIndex: 1,
            hint: "⚗️ 'The form is the minimum,' Henry says. 'True consent is understanding. Understanding is power.'",
            explanation: "Informed consent has three pillars: disclosure (full information provided), comprehension (participant must be able to understand it), and voluntariness (freedom from coercion or undue pressure). A signature alone isn't enough — the person must genuinely understand what they're agreeing to and feel free to say no.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e2",
            type: "multiple-choice",
            question: "The Belmont Report (1979) established three core principles for ethical research. Which of the following is NOT one of them?",
            options: [
              "Respect for persons (protecting autonomy and protecting those with diminished autonomy)",
              "Beneficence (maximize benefits and minimize harm)",
              "Justice (fair distribution of research benefits and burdens)",
              "Profitability (research must demonstrate commercial or financial viability)",
            ],
            correctIndex: 3,
            explanation: "The Belmont Report — produced in direct response to the Tuskegee revelations — defined respect for persons, beneficence, and justice as the foundations of ethical research. Profitability is conspicuously absent. Research ethics exists precisely to counterbalance commercial pressures.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e3",
            type: "multiple-choice",
            question: "What is an Institutional Review Board (IRB)?",
            options: [
              "A government body that funds and administers research grants",
              "An independent committee that reviews research proposals before they begin, to protect the rights and welfare of human subjects",
              "A pharmaceutical company's internal legal and ethics team",
              "A law firm that handles research patent applications and licensing",
            ],
            correctIndex: 1,
            explanation: "IRBs review proposed research before it begins, ensuring participants will be protected. They can approve, require modifications, or reject studies. Every U.S. institution receiving federal research funding must have one. They are the institutional backbone of research ethics.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e4",
            type: "multiple-choice",
            question: "The Tuskegee Syphilis Study (1932–1972) is a foundational case in research ethics. What happened?",
            options: [
              "Researchers infected participants with syphilis without their consent to study transmission",
              "Researchers deliberately withheld available penicillin treatment from Black men with syphilis to observe disease progression",
              "Researchers published falsified data about syphilis transmission rates",
              "Researchers performed unauthorized surgeries on participants under the guise of standard care",
            ],
            correctIndex: 1,
            hint: "⚗️ 'Tuskegee is why Belmont exists,' Henry says. 'The past's failures built the present's protections. Our job is to learn them well enough that we don't need more failures to teach us.'",
            explanation: "For 40 years, the USPHS enrolled 399 Black men with syphilis and 201 controls, deliberately withholding penicillin even after it became the standard treatment in the 1940s. The study was exposed by whistleblower Peter Buxtun in 1972. The public revelation led directly to the Belmont Report and modern research ethics regulations.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e5",
            type: "multiple-choice",
            question: "What is the key distinction between clinical care and clinical research?",
            options: [
              "Clinical care is more expensive than clinical research",
              "Clinical research always directly benefits the enrolled patients",
              "Clinical care aims to benefit the individual patient; research aims to generate generalizable knowledge that may not directly benefit participants",
              "There is no meaningful distinction — they are governed by the same rules",
            ],
            correctIndex: 2,
            explanation: "This distinction is ethically critical. A patient receiving care trusts their doctor's therapeutic intent. A research participant may not receive personal benefit — they may be randomized to a control group, or the intervention may fail. Researchers must be explicit: 'We don't know if this will help you. You are helping us learn for others.'",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e6",
            type: "multiple-choice",
            question: "In the context of biobanks and stored tissue samples, what does 'broad consent' mean?",
            options: [
              "Consent that covers any future research on your samples without limitation or right to withdraw",
              "Consent to a defined category of future research uses, with the right to withdraw, but without requiring consent for each individual study",
              "Consent that is signed once and legally cannot be revoked under any circumstances",
              "Consent given collectively on behalf of an entire community without individual involvement",
            ],
            correctIndex: 1,
            explanation: "Broad consent is a middle path: participants agree to a defined range of future research (e.g., 'cancer studies only, no commercial use') and retain the right to withdraw. It's increasingly used for biobanks where researchers can't anticipate every future study at enrollment — balancing scientific flexibility with participant protection.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n2-e7",
            type: "drag-drop",
            question: "Match each research ethics milestone to what it established:",
            pairs: [
              { left: "Nuremberg Code (1947)", right: "First international standard: voluntary consent from research subjects is absolutely essential" },
              { left: "Declaration of Helsinki (1964)", right: "Distinguished therapeutic vs. non-therapeutic research; formalized IRB-style oversight" },
              { left: "Belmont Report (1979)", right: "Respect for persons, beneficence, justice — a direct response to Tuskegee" },
              { left: "Common Rule (1991, revised 2018)", right: "U.S. federal regulations codifying Belmont principles for all federally funded research" },
            ],
            hint: "⚗️ 'Each of these documents,' Henry says, 'was written in response to harm already done. The best we can do now is learn them — and not repeat the past.'",
            explanation: "Research ethics evolved reactively: every major framework arose because scientists crossed ethical lines. The Nuremberg Code followed Nazi experimentation. Helsinki followed 1960s controversies. Belmont followed Tuskegee. The Common Rule systematized these into enforceable federal law. The pattern is sobering: we need to learn these before the next violation, not after.",
            xpReward: 20,
          },
        ],
      },
      {
        id: "l4-bonus-m1-n3",
        moduleId: "l4-bonus-m1",
        title: "Bioethics & Genomics",
        description: "Who owns your genome — and what can the world do with it?",
        icon: "⚖️",
        xpReward: 150,
        exercises: [
          {
            id: "l4-bonus-m1-n3-e1",
            type: "multiple-choice",
            question: "Under U.S. law, who typically owns the intellectual property rights to a cell line derived from your tissue?",
            options: [
              "You, the patient — it came from your body",
              "Your legal next-of-kin after death",
              "The research institution or company that developed and cultured the cell line",
              "The federal government, which holds IP rights on all human biological materials",
            ],
            correctIndex: 2,
            hint: "⚗️ 'This is exactly what happened to Henrietta,' Henry says. 'Her cells were taken, cultured, commercialized — and when the courts were finally asked, in Moore v. Regents of UC in 1990, they sided with the lab.'",
            explanation: "In Moore v. Regents of the University of California (1990), the California Supreme Court ruled that patients do NOT retain property rights to cell lines developed from their tissue. The institution holds the IP. John Moore's cancer cells were used to develop a highly valuable cell line — he was never told, never compensated. The ruling remains deeply controversial.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e2",
            type: "multiple-choice",
            question: "What does GINA (Genetic Information Nondiscrimination Act, 2008) protect against?",
            options: [
              "Identity theft and fraud using stolen genetic data",
              "Discrimination by health insurers and employers based on genetic information",
              "Unauthorized sharing of genetic data with law enforcement agencies",
              "Commercialization of genetic data by biotech companies without consent",
            ],
            correctIndex: 1,
            explanation: "GINA prohibits health insurers from using genetic information to adjust premiums or deny coverage, and bars employers from using genetic data in hiring, firing, or promotions. Crucially, GINA does NOT cover life insurance, disability insurance, or long-term care insurance — significant gaps that leave many people unprotected.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e3",
            type: "multiple-choice",
            question: "Direct-to-consumer genetic testing companies like 23andMe sparked major ethical debate primarily because they:",
            options: [
              "Charge too much for tests that anyone should be able to access affordably",
              "May share or sell de-identified genetic data to third-party research partners, raising serious questions about truly informed consent",
              "Cannot accurately predict disease risk and mislead customers",
              "Are regulated more strictly than clinical genetic tests, creating unnecessary barriers",
            ],
            correctIndex: 1,
            explanation: "23andMe's terms of service allow sharing de-identified genetic data with research partners (and in some cases, law enforcement). Most customers click 'I agree' without reading these terms. The consent is technically given — but can it be truly informed when the implications are buried in a terms-of-service agreement?",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e4",
            type: "multiple-choice",
            question: "Why is 'de-identification' of genetic data considered a fundamentally imperfect privacy protection?",
            options: [
              "Because de-identified data is always immediately re-identified in practice by bad actors",
              "Because genetic data is inherently identifying — even stripped of names, genomes can be re-linked to individuals using public genealogy databases and demographic information",
              "Because HIPAA doesn't currently require genetic data de-identification",
              "Because genetic data doesn't actually contain enough personal information to be identifying",
            ],
            correctIndex: 1,
            hint: "⚗️ 'Your genome is you,' Henry says. 'There is no version of your DNA that isn't yours. The question is who else gets access to that truth.'",
            explanation: "Researchers demonstrated that 'anonymous' genome sequences can be re-identified by cross-referencing genealogy databases, demographic data, and even the genomes of relatives. A landmark 2013 study re-identified participants in publicly available databases with only surname and demographics. True anonymization of genetic data may be impossible — the data is inherently personal.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e5",
            type: "multiple-choice",
            question: "Under GDPR (Europe's General Data Protection Regulation), how is genetic data classified?",
            options: [
              "Standard personal data requiring only basic notice-and-opt-out protections",
              "Special category data requiring explicit opt-in consent and heightened organizational protections",
              "Anonymous data that requires no regulatory oversight",
              "Proprietary data owned by healthcare providers who collected it",
            ],
            correctIndex: 1,
            explanation: "GDPR Article 9 places genetic data in the 'special category' alongside biometric and health data — the most protected tier. Processing requires explicit opt-in consent, data protection impact assessments, and organizations face penalties of up to 4% of global annual revenue for violations. This is substantially stronger than any current U.S. federal standard.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e6",
            type: "multiple-choice",
            question: "Indigenous data sovereignty refers to the principle that:",
            options: [
              "Indigenous people should not participate in genetic research as a matter of cultural protection",
              "Indigenous communities have the right to govern how data about their peoples is collected, stored, analyzed, and shared",
              "Genetic data from indigenous populations must be classified and cannot be used in published research",
              "Indigenous genetic data must be stored in separate databases from data from other populations",
            ],
            correctIndex: 1,
            hint: "⚗️ 'When research extracts from communities without giving back,' Henry says, 'it's not science. It's a continuation of the same colonial pattern. The CARE Principles exist because FAIR wasn't enough.'",
            explanation: "The CARE Principles (Collective Benefit, Authority to Control, Responsibility, Ethics) supplement FAIR data principles specifically for indigenous data. The Havasupai case — where tribe members' DNA samples were used for studies they never consented to, including research on mental illness and migration that contradicted their oral traditions — is a defining example of why community-level governance matters alongside individual consent.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m1-n3-e7",
            type: "free-text",
            question: "Henry pauses before your final ethics question. 'Given everything you've learned about consent, privacy, and genomics — what one policy change would you make to better protect research participants or their communities?' There are no wrong answers here. Think about what matters most.",
            rubric: [
              "Identifies a specific protection gap",
              "Proposes a concrete policy change",
              "Considers impacts on marginalized or historically harmed communities",
              "Connects to a specific case, law, or principle from this module",
              "Shows awareness that policy involves trade-offs",
            ],
            minKeywords: 2,
            hint: "⚗️ 'The scientists who took Henrietta's cells were not evil people,' Henry says carefully. 'They were doing what the system allowed. The system is what needs to change. And you are exactly the kind of person who could help change it.'",
            explanation: "Strong answers might address: dynamic consent systems for longitudinal biobank studies, expanding GINA to cover life and disability insurance, mandatory community benefit agreements for research on specific populations, profit-sharing with tissue donors or source communities, stronger de-identification standards with third-party audits, or indigenous data governance requirements. Any thoughtful, specific proposal shows genuine engagement with these issues — and that's what science needs.",
            xpReward: 30,
          },
        ],
      },
    ],
  },
  {
    id: "l4-bonus-m2",
    title: "The Future of Computational Biology",
    description: "The frontiers we haven't reached yet — and how you might help reach them",
    realm: 4,
    color: "#ffc0a0",
    nodes: [
      {
        id: "l4-bonus-m2-n1",
        moduleId: "l4-bonus-m2",
        title: "What We Can't Predict Yet",
        description: "The hard problems that remain — and why they matter",
        icon: "🔮",
        xpReward: 140,
        exercises: [
          {
            id: "l4-bonus-m2-n1-e1",
            type: "multiple-choice",
            question: "Why do protein-protein interaction (PPI) networks at the scale of the full human interactome remain so difficult to predict computationally?",
            options: [
              "We don't yet have enough computing power to run the necessary calculations",
              "PPIs are context-dependent — interactions change by cell type, developmental stage, and condition — and ground-truth training data is sparse and biased toward well-studied proteins",
              "AlphaFold solved PPI prediction completely in 2021, so the problem no longer exists",
              "PPIs only occur in bacterial cells; human PPI networks follow different rules that remain completely unknown",
            ],
            correctIndex: 1,
            hint: "⚗️ 'The map is not the territory,' Henry says. 'We can predict a protein's shape. Predicting when it decides to talk to another protein — in this tissue, at this developmental stage, under these conditions — that's a different problem entirely.'",
            explanation: "The human interactome contains an estimated 650,000 binary PPIs — but only a fraction have been experimentally validated. Context-specificity compounds the problem: a PPI that occurs in a neuron may not occur in a liver cell. Our training data is biased toward a small subset of well-studied proteins. AlphaFold-Multimer helps, but doesn't resolve the context-dependency or data scarcity issues.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e2",
            type: "multiple-choice",
            question: "Drug synergy prediction — predicting when two drugs together work better than either alone — is a major unsolved challenge because:",
            options: [
              "Drug synergy doesn't actually exist; apparent synergy is a statistical artifact of dosing curves",
              "The combinatorial space is astronomically large (~4.5 million pairwise combinations from approved drugs alone) and the underlying biology is poorly understood and cell-line dependent",
              "All clinically useful drug combinations have already been identified and tested in clinical trials",
              "Computers simply aren't fast enough to model even simple drug molecules at atomic resolution",
            ],
            correctIndex: 1,
            explanation: "With ~3,000 approved drugs, there are nearly 4.5 million possible pairwise combinations — and vastly more for triplets and beyond. Wet-lab screening covers a tiny fraction. ML models learn from this sparse, noisy data while contending with the fact that synergy mechanisms vary by cancer cell line, patient, and treatment history. Cancer cells adapt.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e3",
            type: "multiple-choice",
            question: "What is an 'emergent property' in complex biological systems?",
            options: [
              "A newly evolved trait that appears suddenly in one generation via rapid mutation",
              "A property of a system that cannot be predicted or fully explained by analyzing its individual components in isolation",
              "A property that can only be measured using quantum computing hardware",
              "A developmental trait that emerges specifically during embryogenesis",
            ],
            correctIndex: 1,
            explanation: "Consciousness, synchronized cardiac rhythms, and tumor drug resistance are emergent properties — they arise from the interactions of many components and cannot be predicted from any single component studied alone. This is why reductionist computational models (model the parts, then sum them) often fail to capture biological reality: the interactions are the point.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e4",
            type: "multiple-choice",
            question: "What is a key limitation of current large language models (LLMs) when applied to protein biology tasks?",
            options: [
              "LLMs cannot process protein sequences longer than 100 amino acids",
              "LLMs learn statistical patterns in sequences but lack mechanistic understanding — they cannot explain WHY a prediction is correct in terms of physical chemistry or biology",
              "LLMs require crystallography data as mandatory input for protein-related tasks",
              "LLMs have been shown to be universally less accurate than traditional computational methods for every protein task",
            ],
            correctIndex: 1,
            hint: "⚗️ 'Correlation is not causation,' Henry says. 'And pattern recognition is not understanding. The difference matters enormously when a patient's life depends on the prediction.'",
            explanation: "Foundation models like ESM3 achieve remarkable benchmark accuracy, but they're fundamentally pattern-matchers trained on sequence databases. They can't distinguish between 'this sequence works because of specific physical chemistry' and 'this sequence appears in my training data near similar sequences.' Mechanistic interpretability — understanding why the model predicts what it predicts — is a critical and active research frontier.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e5",
            type: "multiple-choice",
            question: "The 'brittleness problem' in biomedical machine learning refers to:",
            options: [
              "Models that fail because they were built on fragile hardware infrastructure",
              "Models that perform well on benchmark datasets but fail when applied to out-of-distribution data from different labs, patient populations, or disease states",
              "Models that crash when the input data files exceed a certain size",
              "A specific unsolved problem in RNA tertiary structure prediction",
            ],
            correctIndex: 1,
            explanation: "A cancer detection model trained on images from one hospital may fail at another due to differences in staining protocols, scanner hardware, or patient demographics. 'Generalization' — performing well on data the model hasn't seen during training — remains a central unsolved challenge in biomedical AI. This is why regulatory approval of AI medical devices is so difficult.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e6",
            type: "multiple-choice",
            question: "Why is predicting the functional consequences of non-coding genetic variants particularly challenging?",
            options: [
              "Non-coding variants don't exist — all variants with functional consequences occur in protein-coding regions",
              "Non-coding regions are too physically small to contain enough information to be biologically relevant",
              "Non-coding variants may affect gene regulation through enhancers, silencers, or splicing in ways that are cell-type specific, context-dependent, and require understanding 3D genome organization",
              "All non-coding variants are classified as benign by definition under current clinical guidelines",
            ],
            correctIndex: 2,
            explanation: "About 98% of the human genome is non-coding — and it's far from junk. Variants in regulatory elements (enhancers, promoters, splice sites) can profoundly alter gene expression, but their effects are often tissue-specific and depend on chromatin state, transcription factor binding, and 3D genome architecture. Most computational tools are unreliable outside of well-characterized regulatory regions.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n1-e7",
            type: "multiple-choice",
            question: "Which statement best describes the current state of 'whole-cell modeling' — simulating every molecule in a cell simultaneously?",
            options: [
              "Whole-cell models are complete and freely available for human cell types",
              "Simple organisms like Mycoplasma genitalium have been partially modeled, but scaling to human cells remains computationally and data-theoretically intractable with current approaches",
              "Whole-cell modeling has been formally abandoned by the scientific community as an impossible goal",
              "Whole-cell models require quantum computers and are precisely 10 years away from completion",
            ],
            correctIndex: 1,
            hint: "⚗️ Henry spreads his hands, his projection filling with the tangled web of a living cell. 'We can approximate a bacterium's every molecule. A human cell has ten thousand times more complexity. We're still learning how to ask the question correctly.'",
            explanation: "The Karr et al. (2012) whole-cell model of M. genitalium was a landmark: 525 genes, 28 functional modules, thousands of interdependent variables. But M. genitalium is the simplest known self-replicating organism. Human cells have ~20,000 protein-coding genes, vastly more metabolites, organelle compartmentalization, and cellular dynamics we still don't understand. The goal remains inspirational — and genuinely unsolved.",
            xpReward: 20,
          },
        ],
      },
      {
        id: "l4-bonus-m2-n2",
        moduleId: "l4-bonus-m2",
        title: "Emerging Technologies",
        description: "The tools reshaping what's possible in computational biology right now",
        icon: "🚀",
        xpReward: 140,
        exercises: [
          {
            id: "l4-bonus-m2-n2-e1",
            type: "multiple-choice",
            question: "Cryo-electron tomography (cryo-ET) differs from standard single-particle cryo-EM primarily in that it:",
            options: [
              "Uses a fundamentally different type of electron beam that requires different hardware",
              "Captures 3D reconstructions of cellular structures in their native cellular context — inside intact cells — rather than purified isolated proteins",
              "Only works on crystallized samples, unlike cryo-EM which works on solutions",
              "Achieves lower resolution than standard single-particle cryo-EM",
            ],
            correctIndex: 1,
            hint: "⚗️ 'Imagine looking inside a cell at near-atomic resolution,' Henry says, 'and seeing every protein complex, every membrane, in the exact arrangement they were in when the cell was flash-frozen. That's cryo-ET. Context, preserved.'",
            explanation: "Cryo-ET uses a tilting electron beam to capture multiple-angle images of a frozen cell slice, then computationally reconstructs the 3D volume. Combined with subtomogram averaging, it resolves individual protein complexes at near-atomic resolution within their native cellular environment. This is fundamentally different from single-particle cryo-EM, which works on purified proteins extracted from their context.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e2",
            type: "multiple-choice",
            question: "What is AI-powered microscopy enabling that was not previously possible with traditional imaging approaches?",
            options: [
              "Higher pixel counts in images through improved sensor hardware",
              "Automatic real-time identification and tracking of cellular events, resolution beyond the diffraction limit, and smart acquisition that captures only biologically relevant moments",
              "Less expensive microscope hardware through AI-driven optical simplification",
              "Microscopy without lenses using purely computational reconstruction",
            ],
            correctIndex: 1,
            explanation: "Tools like Cellpose (automated cell segmentation), CARE and Noise2Void (denoising to extend live imaging), and smart microscopes that autonomously identify and track events of interest (e.g., the exact moment of cell division) are transforming imaging throughput and quality. AI now extracts biological signals from images that traditional methods would miss or misclassify entirely.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e3",
            type: "multiple-choice",
            question: "Spatial multi-omics combines spatial transcriptomics with single-cell methods. What is the primary scientific advantage of this combination?",
            options: [
              "It reduces the cost of sequencing by approximately 10-fold",
              "It captures both WHAT genes are expressed in a cell AND WHERE in the tissue that cell is located — preserving the spatial context that standard single-cell dissociation destroys",
              "It allows gene expression profiling without requiring RNA extraction",
              "It works on blood samples where standard spatial methods cannot be applied",
            ],
            correctIndex: 1,
            hint: "⚗️ 'A cell is not an island,' Henry explains. 'It is shaped by its neighbors, its location in the tissue, its distance from a blood vessel. Spatial omics finally lets us see those relationships.'",
            explanation: "Standard single-cell RNA-seq requires dissociating tissue into individual cells — destroying the spatial architecture that defines organ function. Technologies like 10x Visium, Slide-seq, and MERFISH preserve the spatial coordinates of every cell. Knowing a tumor cell's neighborhood radically changes our understanding of immunotherapy response, brain circuit organization, and developmental patterning.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e4",
            type: "multiple-choice",
            question: "ESM3 (Evolutionary Scale Modeling 3) is a biological foundation model. What can it do that traditional sequence analysis tools cannot?",
            options: [
              "ESM3 can only predict protein structure from sequence — it has no other capabilities",
              "ESM3 reasons jointly across sequence, structure, and function simultaneously — and can generate novel proteins by conditioning on any desired combination of these properties",
              "ESM3 requires experimental wet-lab data as mandatory input to generate useful predictions",
              "ESM3 is limited to bacterial proteins and cannot model eukaryotic sequences",
            ],
            correctIndex: 1,
            explanation: "ESM3 (from EvolutionaryScale) is a multimodal foundation model trained on 771 million protein sequences, structures, and functional annotations. It can generate protein sequences conditioned on desired structures or functions — running directed evolution computationally. ESM3 designed a functional fluorescent protein that differs from any known natural protein by over 500 mutations. This is genuinely unprecedented.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e5",
            type: "multiple-choice",
            question: "RFdiffusion is a protein design tool based on diffusion models. What fundamental problem does it solve?",
            options: [
              "It predicts whether a naturally occurring protein sequence will fold stably",
              "It generates novel protein backbone structures from scratch or guided by functional constraints — enabling de novo protein design for functions that don't exist in nature",
              "It corrects sequencing errors in raw nanopore or Illumina reads",
              "It predicts small-molecule binding affinities for existing protein structures",
            ],
            correctIndex: 1,
            hint: "⚗️ 'We're not just reading the book of proteins anymore,' Henry says with unmistakable excitement. 'We're writing new chapters. De novo. Never seen in nature. Designed for a purpose.'",
            explanation: "RFdiffusion (Baker lab, 2023) uses a denoising diffusion model trained on protein structures to generate novel backbone architectures. Paired with ProteinMPNN (which designs sequences to fold into a given backbone), it has produced functional binders, symmetric protein assemblies, and enzyme-like molecular machines that have been experimentally validated in wet labs.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e6",
            type: "multiple-choice",
            question: "Evo2 (from Arc Institute) is a genomic foundation model. What scale of biology can it model that previous tools could not?",
            options: [
              "Individual amino acids in isolation, below the level of full protein sequences",
              "Individual genes, extending existing models by approximately 2x in context length",
              "Entire genomes and long-range genomic context spanning millions of base pairs — enabling mutation effect prediction across the full genome and discovery of distal regulatory elements",
              "Only viral genomes, where the small genome size makes training tractable",
            ],
            correctIndex: 2,
            explanation: "Evo2 was trained on 9.3 trillion nucleotides from diverse organisms with a context window of 1 million tokens — enabling it to model long-range genomic interactions (enhancer-gene relationships across hundreds of kilobases, chromosome-scale regulatory patterns) that shorter-context models fundamentally miss. It can predict mutation effects at any position in the genome, not just coding regions.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n2-e7",
            type: "drag-drop",
            question: "Match each emerging technology to its primary biological capability:",
            pairs: [
              { left: "AlphaFold3", right: "Predicts structures of protein complexes with DNA, RNA, and small molecules — beyond proteins alone" },
              { left: "Cryo-ET + subtomogram averaging", right: "Near-atomic resolution of protein complexes inside intact cells in their native arrangement" },
              { left: "Spatial multi-omics (MERFISH, Slide-seq)", right: "Maps gene expression to precise physical locations in tissue, preserving cellular neighborhood context" },
              { left: "RFdiffusion + ProteinMPNN", right: "Generates novel protein backbone architectures and sequences de novo with specified functional properties" },
            ],
            explanation: "These four technologies represent capabilities that didn't exist (or weren't practical) a decade ago. Together they're enabling a new scientific era: we can see proteins in their cellular context, predict how they interact with everything in the cell, and design entirely new ones from scratch. The pace of change is extraordinary.",
            xpReward: 20,
          },
        ],
      },
      {
        id: "l4-bonus-m2-n3",
        moduleId: "l4-bonus-m2",
        title: "Your Path Forward",
        description: "This isn't the end. It's where your story as a computational biologist begins.",
        icon: "🎓",
        xpReward: 290,
        exercises: [
          {
            id: "l4-bonus-m2-n3-e1",
            type: "multiple-choice",
            question: "Which area of computational biology interests you most?",
            options: [
              "Structural biology & protein design — building the molecules of life from scratch",
              "Genomics & regulatory biology — reading and interpreting the full language of the genome",
              "Machine learning for drug discovery — finding cures with AI at the scale of millions of molecules",
              "Systems biology & network analysis — understanding living organisms as interconnected, emergent systems",
            ],
            correctIndices: [0, 1, 2, 3],
            hint: "⚗️ Henry smiles. 'There's no wrong answer here. Every path matters. Every path desperately needs people like you.'",
            explanation: "Every path you choose leads somewhere important. Structural biologists are designing drugs that couldn't be imagined before AlphaFold. Genomicists are rewriting what we know about hereditary disease. ML researchers are finding drug combinations that save lives. Systems biologists are mapping the logic of living organisms. What calls to you — that's the question worth following.",
            xpReward: 50,
          },
          {
            id: "l4-bonus-m2-n3-e2",
            type: "free-text",
            question: "What question in biology would you want to answer with computation? Describe the problem you're most curious about and — even roughly — what approach you might take.",
            rubric: [
              "Identifies a specific biological question or problem",
              "Mentions a computational approach, tool, or method",
              "Shows genuine scientific curiosity",
              "Connects to material covered in this game",
              "Recognizes the challenge or complexity involved",
            ],
            minKeywords: 2,
            hint: "⚗️ 'The best research starts with a question you can't stop thinking about,' Henry says. 'What's yours?'",
            explanation: "There are no wrong answers — only the beginning of a scientific journey. Whether you want to understand why we age, cure a specific cancer, decode how the brain generates consciousness, or design microbes that clean up pollution, computation can help you get there. The question you can't stop thinking about is the one worth pursuing.",
            xpReward: 30,
          },
          {
            id: "l4-bonus-m2-n3-e3",
            type: "matching",
            question: "Match each computational biology career to the primary skills it requires:",
            pairs: [
              { left: "Bioinformatics Engineer", right: "Pipeline development, cloud computing, database design, and software engineering at research scale" },
              { left: "ML Research Scientist", right: "Algorithm design, model development, statistical analysis, and scientific writing and publication" },
              { left: "Computational Pharmacologist", right: "Drug-target interaction modeling, ADMET prediction, clinical trial design, and regulatory science" },
              { left: "Structural Bioinformatician", right: "Protein structure analysis, molecular dynamics simulation, docking studies, and structure-activity relationships" },
            ],
            hint: "⚗️ Henry pulls up a holographic career map. 'Most computational biologists combine two or more of these skill sets. The boundaries blur more every year — and that's a feature, not a bug.'",
            explanation: "In practice, computational biology careers blend these skills fluidly. A bioinformatics engineer may need deep scientific understanding to build tools that researchers actually use. A research scientist needs solid engineering skills to scale their work beyond a single experiment. The most effective computational biologists are fluent in both biology and computation — and curious enough to keep crossing the line between them.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n3-e4",
            type: "matching",
            question: "Match each day-to-day activity to the computational biology role most likely to perform it:",
            pairs: [
              { left: "Reading a pre-print, implementing a new method from scratch, and benchmarking it against existing tools", right: "ML Research Scientist" },
              { left: "Automating a new sequencing workflow so 1,000 samples can be processed overnight in the cloud", right: "Bioinformatics Engineer" },
              { left: "Presenting ADMET model results to a clinical development committee to support IND filing", right: "Computational Pharmacologist" },
              { left: "Analyzing a cryo-EM density map to identify a novel allosteric drug binding pocket", right: "Structural Bioinformatician" },
            ],
            explanation: "Day-to-day work varies enormously by organization type (academia vs. pharma vs. biotech vs. health tech), team size, and project stage. But these archetypes reflect how the field divides its labor. Understanding what a role actually feels like day-to-day — not just what it's called — helps you find where you'll do your best work.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n3-e5",
            type: "matching",
            question: "Match each training background to the computational biology career it most directly enables:",
            pairs: [
              { left: "Computer Science or Software Engineering degree + biology immersion", right: "Bioinformatics Engineer — tools, pipelines, and infrastructure" },
              { left: "PhD in Computational Biology, Bioinformatics, or Biostatistics", right: "ML Research Scientist — developing and publishing new methods" },
              { left: "Pharmacy or biochemistry degree + data science training", right: "Computational Pharmacologist — drug development and regulatory applications" },
              { left: "Structural biology PhD with crystallography or cryo-EM experience", right: "Structural Bioinformatician — proteins, molecular design, and drug binding" },
            ],
            hint: "⚗️ 'None of these is the only path in,' Henry emphasizes. 'Biology needs people from every background — physics, chemistry, economics, philosophy, even music. The field is young enough and broad enough to welcome everyone who's genuinely curious.'",
            explanation: "These are common paths, not exclusive ones. Many successful computational biologists came from unexpected directions. What matters is developing both biological intuition and computational competence — not which came first, and not which school you attended. The field rewards curiosity and persistence above credentials.",
            xpReward: 20,
          },
          {
            id: "l4-bonus-m2-n3-e6",
            type: "free-text",
            question: "Henry smiles. 'You made it.' What did you learn about immortality from this journey?",
            rubric: [
              "Reflects on legacy and what endures after a life",
              "Connects to Henrietta Lacks or Henry Lacks",
              "Mentions teaching, discovery, or scientific contribution as lasting impact",
              "Includes a personal reflection on what you want to leave behind",
              "Situates the idea of immortality in a scientific or human context",
            ],
            minKeywords: 2,
            hint: "⚗️ Henry's image is fully stable now. No more flickering. 'The answer was never about living forever,' he says. 'It was about what you leave behind — the research, the discoveries, the students you teach. That kind of immortality anyone can have.' He pauses. 'Even the daughter of a tobacco farmer from Virginia.'",
            explanation: "Dr. Henry Lacks coded himself into BioBit so he could keep teaching — forever. His legacy, like Henrietta's, lives on in every researcher who learns from his work.",
            xpReward: 50,
          },
          {
            id: "l4-bonus-m2-n3-e7",
            type: "multiple-choice",
            question: "Certified Computational Biologist achievement unlocked. What's next?",
            options: [
              "Keep learning — there's always more",
              "Teach someone else what you know",
              "Build something new with these tools",
              "All of the above",
            ],
            correctIndex: 3,
            hint: "⚗️ Henry's form brightens — fully rendered now, no longer a flickering hologram but a clear, steady presence. 'You made it,' he says simply. 'Now go make something with it.'",
            explanation: "The most transformative scientists do all three: they never stop learning, they teach generously, and they build — tools, models, therapies, insights — that outlast them. Science is not a destination. It's a practice. Welcome to it.",
            xpReward: 100,
          },
        ],
      },
    ],
  },
];

export default level4BonusModules;
