import type { Module } from "@/lib/types";

const level3AdvancedModules: Module[] = [
  {
    id: "l3-adv-m1",
    title: "Gradient Descent & Optimization",
    description: "The mechanics of how neural networks actually learn",
    realm: 3,
    color: "#a855f7",
    nodes: [
      {
        id: "l3-adv-m1-n1",
        moduleId: "l3-adv-m1",
        title: "Loss Functions",
        description: "MSE vs cross-entropy vs BCE — choosing the right loss for your task",
        icon: "📉",
        xpReward: 220,
        exercises: [
          {
            id: "l3-adv-m1-n1-e1",
            type: "multiple-choice",
            question: "What is the mathematical form of Mean Squared Error (MSE)?",
            options: [
              "MSE = (1/n) Σ |y_pred - y_true|",
              "MSE = (1/n) Σ (y_pred - y_true)²",
              "MSE = -Σ y_true · log(y_pred)",
              "MSE = max(0, 1 - y_true · y_pred)",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: MSE squares the difference between predicted and true values, then averages across all samples.\n\nIntuition: Squaring penalizes large errors much more than small ones — a prediction off by 10 is 100 times worse than one off by 1, not 10 times.\n\nNote: This makes MSE sensitive to outliers, which matters a lot in biological data.",
            explanation: "MSE = (1/n) Σ (y_pred - y_true)². The squaring ensures all terms are positive and emphasizes larger errors.",
            xpReward: 15,
          },
          {
            id: "l3-adv-m1-n1-e2",
            type: "drag-drop",
            question: "Match each loss function to its ideal use case:",
            pairs: [
              { left: "Mean Squared Error (MSE)", right: "Predicting continuous gene expression levels" },
              { left: "Binary Cross-Entropy (BCE)", right: "Classifying a tumor as malignant or benign (0/1)" },
              { left: "Categorical Cross-Entropy", right: "Predicting cell type from 20 possible classes" },
              { left: "Huber Loss", right: "Regression with outliers — robust to extreme values" },
            ],
            hint: "🌌 TEACHING: Loss function choice should match your output type: continuous → MSE/Huber, binary → BCE, multi-class → CCE.\n\nIntuition: Using MSE for classification would treat 'almost cancer' and 'definitely cancer' as equally wrong — BCE understands probabilities.\n\nNote: In bioinformatics, RNA-seq counts are often log-transformed before MSE to handle the massive dynamic range.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n1-e3",
            type: "multiple-choice",
            question: "Cross-entropy loss is defined as H(y, ŷ) = -Σ y · log(ŷ). What happens to this loss when the model predicts probability 0.01 for the correct class?",
            options: [
              "The loss is approximately 0 — a confident wrong prediction is fine",
              "The loss is -log(0.01) ≈ 4.6 — very high penalty for confident wrong predictions",
              "The loss is 0.01 — proportional to the predicted probability",
              "The loss is undefined because log(0) is undefined",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: -log(0.01) = log(100) ≈ 4.6. Cross-entropy harshly penalizes confident wrong predictions.\n\nIntuition: If you're 99% sure a patient doesn't have cancer and they do, that's a catastrophic mistake — cross-entropy reflects this severity.\n\nNote: This is why we need softmax outputs to stay away from 0 and 1 in practice (numerical stability).",
            explanation: "Cross-entropy = -log(0.01) ≈ 4.6. The log function goes to -∞ as the argument approaches 0, creating a very steep penalty for confident wrong predictions.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n1-e4",
            type: "multiple-choice",
            question: "Why is Binary Cross-Entropy (BCE) preferred over MSE for binary classification tasks?",
            options: [
              "BCE is always faster to compute than MSE",
              "BCE treats outputs as probabilities and has steeper gradients when the model is confidently wrong",
              "MSE cannot handle values between 0 and 1",
              "BCE prevents overfitting automatically",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: BCE is derived from maximum likelihood estimation under a Bernoulli distribution — it's the theoretically correct loss for binary probabilities.\n\nIntuition: With MSE, predicting 0.4 vs 0.6 for a true label of 1 both give small losses. BCE punishes 0.4 much harder — you're almost wrong.\n\nNote: MSE on sigmoid outputs creates vanishing gradients when predictions are near 0 or 1.",
            explanation: "BCE = -[y·log(ŷ) + (1-y)·log(1-ŷ)]. It provides stronger gradient signal when the model is confidently incorrect, improving learning.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n1-e5",
            type: "fill-blank",
            question: "Complete the sentence: When predicting a patient's blood pressure from genomic features (a continuous value), you should use ___ loss. When predicting whether a patient has diabetes (yes/no), you should use ___ loss.",
            blanks: [
              { text: "MSE or Huber", answer: "MSE", position: 0 },
              { text: "Binary Cross-Entropy", answer: "BCE", position: 1 },
            ],
            hint: "🌌 TEACHING: Match the loss to the output type — continuous outputs need regression losses, discrete class predictions need classification losses.\n\nIntuition: Using the wrong loss is like grading a multiple-choice exam with an essay rubric — the feedback is meaningless.\n\nNote: For survival analysis (time-to-event), specialized losses like Cox proportional hazard loss are used.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n1-e6",
            type: "free-text",
            question: "A colleague trains a cancer detection model and achieves very low MSE. But when you look at the predictions, the model always outputs ~0.3 regardless of the input. Why is low MSE not sufficient here, and what loss would you switch to?",
            rubric: [
              "identifies that MSE rewards predicting the mean (class imbalance problem)",
              "notes the model learned a trivial constant prediction",
              "suggests Binary Cross-Entropy or mentions AUC as evaluation metric",
            ],
            hint: "🌌 TEACHING: With imbalanced classes (e.g., 5% cancer), predicting 0.05 for everyone gives near-zero MSE but is clinically useless.\n\nIntuition: Grading a cancer screener by average error rewards always saying 'no cancer' if cancer is rare.\n\nNote: This is why medical ML models must be evaluated with metrics like AUC-ROC, not just MSE.",
            xpReward: 35,
          },
        ],
      },
      {
        id: "l3-adv-m1-n2",
        moduleId: "l3-adv-m1",
        title: "Optimizers",
        description: "SGD vs Adam vs RMSprop — how we navigate the loss landscape",
        icon: "⚙️",
        xpReward: 230,
        exercises: [
          {
            id: "l3-adv-m1-n2-e1",
            type: "multiple-choice",
            question: "Stochastic Gradient Descent (SGD) updates parameters using:",
            options: [
              "The gradient computed over the entire training dataset",
              "The gradient computed on a single randomly sampled data point (or mini-batch)",
              "The average gradient over the last 10 epochs",
              "A random perturbation in parameter space",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: 'Stochastic' means random — SGD picks a random sample (or mini-batch) each step instead of using the full dataset.\n\nIntuition: Instead of surveying every voter before deciding policy, you ask a random sample. Faster but noisier.\n\nNote: In practice 'SGD' often means mini-batch SGD — using batches of 32-256 samples per step.",
            explanation: "SGD computes gradients on a random mini-batch, making it much faster per step than full-batch gradient descent, though noisier.",
            xpReward: 15,
          },
          {
            id: "l3-adv-m1-n2-e2",
            type: "sequence-order",
            question: "Order these optimizers from simplest to most sophisticated:",
            items: ["Vanilla SGD", "SGD with Momentum", "RMSprop", "Adam"],
            correctOrder: [0, 1, 2, 3],
            hint: "🌌 TEACHING: Each optimizer builds on the last: SGD → add momentum → add adaptive LR (RMSprop) → combine both (Adam).\n\nIntuition: SGD is a ball rolling downhill. Momentum adds inertia. RMSprop adjusts step size per parameter. Adam does both.\n\nNote: Adam is the default choice for most deep learning today, including transformers.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n2-e3",
            type: "multiple-choice",
            question: "What does 'momentum' add to SGD?",
            options: [
              "A larger learning rate to speed up convergence",
              "An exponentially weighted moving average of past gradients, smoothing the update direction",
              "Automatic adjustment of the learning rate per parameter",
              "L2 regularization on the weights",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Momentum accumulates a velocity vector in the direction of persistent gradients, dampening oscillations.\n\nIntuition: A ball rolling downhill builds up speed in the consistent direction while averaging out left-right wobbles.\n\nNote: Typical momentum value is 0.9 — 90% previous velocity + 10% current gradient.",
            explanation: "Momentum: v_t = β·v_{t-1} + (1-β)·g_t; θ = θ - α·v_t. The velocity v accumulates consistent gradient directions and dampens noisy oscillations.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n2-e4",
            type: "drag-drop",
            question: "Match each learning rate schedule to what it does:",
            pairs: [
              { left: "Step Decay", right: "Reduce LR by a fixed factor every N epochs" },
              { left: "Cosine Annealing", right: "Smoothly decrease LR following a cosine curve to near-zero" },
              { left: "Warmup", right: "Start with very small LR, then ramp up — stabilizes early transformer training" },
              { left: "ReduceLROnPlateau", right: "Decrease LR when validation loss stops improving" },
            ],
            hint: "🌌 TEACHING: Learning rate schedules help navigate loss landscapes — high LR for fast early progress, low LR for fine-tuning near minima.\n\nIntuition: Drive fast on the highway, then slow down as you approach the parking spot.\n\nNote: Warmup is critical for transformers — without it, early gradient updates are so large they destabilize training.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n2-e5",
            type: "multiple-choice",
            question: "Adam optimizer maintains two running averages per parameter: m_t (first moment) and v_t (second moment). What do these represent?",
            options: [
              "m_t = mean of weights; v_t = variance of weights",
              "m_t = exponential moving average of gradients; v_t = exponential moving average of squared gradients",
              "m_t = learning rate; v_t = momentum coefficient",
              "m_t = batch mean; v_t = batch variance",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Adam = Adaptive Moment Estimation. m_t tracks gradient direction (momentum), v_t tracks gradient magnitude per parameter.\n\nIntuition: m_t says 'which way are we consistently going?'; v_t says 'how bumpy is this direction?' — Adam takes bigger steps where it's smooth.\n\nNote: The bias correction (dividing by 1-β^t) prevents the estimates from being too small early in training.",
            explanation: "Adam: m_t = β1·m_{t-1} + (1-β1)·g_t; v_t = β2·v_{t-1} + (1-β2)·g_t². The update is θ -= α · m̂_t / (√v̂_t + ε).",
            xpReward: 25,
          },
          {
            id: "l3-adv-m1-n2-e6",
            type: "free-text",
            question: "A researcher trains a genomics model with Adam and achieves 92% validation accuracy. A second researcher uses vanilla SGD and achieves 91% but the model generalizes better to a new hospital's data. Why might SGD generalize better even with lower validation accuracy?",
            rubric: [
              "mentions SGD noise can help escape sharp minima",
              "references flat vs sharp minima and generalization",
              "notes validation accuracy ≠ test generalization (dataset shift)",
            ],
            hint: "🌌 TEACHING: SGD's noisy updates often converge to flatter minima, which generalize better than the sharp minima Adam finds.\n\nIntuition: A flat valley stays low even if you move slightly sideways. A sharp spike drops off quickly — a small distribution shift and you fall off.\n\nNote: This is an active research area. Some practitioners use Adam for fast convergence, then switch to SGD for final fine-tuning.",
            xpReward: 30,
          },
        ],
      },
      {
        id: "l3-adv-m1-n3",
        moduleId: "l3-adv-m1",
        title: "Training Dynamics",
        description: "Overfitting, bias-variance tradeoff, and regularization strategies",
        icon: "🎛️",
        xpReward: 240,
        exercises: [
          {
            id: "l3-adv-m1-n3-e1",
            type: "multiple-choice",
            question: "A model achieves 99% training accuracy but 60% validation accuracy. This is a classic sign of:",
            options: [
              "Underfitting — the model is too simple",
              "Overfitting — the model memorized training data including noise",
              "Dataset shift — train and validation come from different distributions",
              "Label noise — the training labels are incorrect",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: When train accuracy >> validation accuracy, the model has memorized noise specific to the training set rather than learning the true signal.\n\nIntuition: A student who memorizes every past exam answer word-for-word fails when questions are rephrased.\n\nNote: Check the gap, not just the numbers. A gap > 10% usually warrants investigation.",
            explanation: "The large train-validation gap indicates overfitting. The model learned the noise in training data and fails to generalize.",
            xpReward: 15,
          },
          {
            id: "l3-adv-m1-n3-e2",
            type: "drag-drop",
            question: "Match each regularization technique to how it works:",
            pairs: [
              { left: "L2 Regularization (Weight Decay)", right: "Adds λ·||w||² to loss — penalizes large weights, pushes them toward zero" },
              { left: "L1 Regularization (Lasso)", right: "Adds λ·||w||₁ to loss — produces sparse weights, drives some to exactly zero" },
              { left: "Dropout", right: "Randomly zeros out neurons during training — forces redundant representations" },
              { left: "Early Stopping", right: "Halt training when validation loss stops improving — prevents overfit epochs" },
            ],
            hint: "🌌 TEACHING: Regularization constrains the model's capacity to memorize — each technique approaches this differently.\n\nIntuition: L2 is like a penalty for extravagance — keep weights small. L1 is like Marie Kondo — eliminate weights that don't spark joy (set to zero). Dropout makes the model learn multiple ways to solve the problem.\n\nNote: In genomics, L1 is especially useful for feature selection — which genes actually matter?",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n3-e3",
            type: "multiple-choice",
            question: "The bias-variance tradeoff states that:",
            options: [
              "Models with high bias overfit; models with high variance underfit",
              "Total expected error = Bias² + Variance + Irreducible noise; reducing one often increases the other",
              "Bias and variance can both be minimized simultaneously with enough data",
              "Bias measures how often the model is wrong; variance measures the magnitude of errors",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Simple models have high bias (wrong assumptions) but low variance (consistent). Complex models have low bias but high variance (sensitive to which data you train on).\n\nIntuition: A simple model always guesses the average — biased but consistent. A complex model perfectly fits each dataset but varies wildly between them.\n\nNote: More data reduces variance without increasing bias — why large datasets are so powerful in ML.",
            explanation: "MSE = Bias² + Variance + Noise. A simple linear model has high bias but low variance; a deep network has low bias but potentially high variance if not regularized.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n3-e4",
            type: "multiple-choice",
            question: "Dropout with rate p=0.5 means during training:",
            options: [
              "50% of the training data is randomly discarded each epoch",
              "Each neuron's output is set to zero with probability 0.5 independently at each forward pass",
              "The learning rate is halved every epoch",
              "Half of the layers are frozen and not updated",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Dropout randomly disables neurons each forward pass, forcing the network to not rely on any single neuron — like cross-training in sports.\n\nIntuition: If your star player could be randomly benched during any play, every other player must be able to pick up their role.\n\nNote: At inference time, dropout is disabled and outputs are scaled by (1-p) to account for the expected activation level.",
            explanation: "During training, each neuron independently has a p=0.5 chance of being zeroed out. This prevents co-adaptation and acts as implicit ensemble training.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n3-e5",
            type: "sequence-order",
            question: "Order these actions when diagnosing a model that performs poorly on validation data (start with diagnosis):",
            items: [
              "Plot training vs validation loss curves to confirm overfitting",
              "Add dropout layers or increase L2 weight decay",
              "Collect more training data or augment existing data",
              "Evaluate final performance on held-out test set",
            ],
            correctOrder: [0, 1, 2, 3],
            hint: "🌌 TEACHING: Diagnose before treating — confirm it's actually overfitting (not underfitting or data issues) before applying regularization.\n\nIntuition: A doctor orders tests before prescribing medication.\n\nNote: Data augmentation (e.g., adding noise to gene expression values) is often more effective than regularization alone.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m1-n3-e6",
            type: "free-text",
            question: "A genomics lab trains a cell-type classifier. With 1,000 training cells it achieves 70% accuracy. With 10,000 cells it achieves 88%. With 100,000 cells it achieves 91%. Why does accuracy improve with more data? At what point does more data stop helping, and what limits performance then?",
            rubric: [
              "explains variance reduction with more training samples",
              "notes diminishing returns — irreducible noise sets a ceiling",
              "mentions label noise or biological variability as the remaining limit",
            ],
            hint: "🌌 TEACHING: More data reduces variance by giving the model more examples to generalize from, but irreducible noise (Bayes error) limits the ceiling.\n\nIntuition: Reading 100 books vs 1,000 vs 10,000 improves your knowledge but at some point you hit the limit of what's knowable from books alone.\n\nNote: In biology, label noise is a real limit — cell types exist on a continuum, and human annotation of 'cell type' has inherent disagreement.",
            xpReward: 35,
          },
        ],
      },
    ],
  },
  {
    id: "l3-adv-m2",
    title: "Transformers & Attention",
    description: "The architecture behind GPT, BERT, and modern protein language models",
    realm: 3,
    color: "#a855f7",
    nodes: [
      {
        id: "l3-adv-m2-n1",
        moduleId: "l3-adv-m2",
        title: "Self-Attention Mechanism",
        description: "Q/K/V matrices, attention weights, and why dot-product attention works",
        icon: "🔭",
        xpReward: 250,
        exercises: [
          {
            id: "l3-adv-m2-n1-e1",
            type: "multiple-choice",
            question: "In self-attention, what do Q (Query), K (Key), and V (Value) represent?",
            options: [
              "Q = question tokens; K = known answers; V = verified outputs",
              "Q = what we're looking for; K = what each position offers; V = the content we retrieve based on match",
              "Q = quantization; K = kernel; V = vector embedding",
              "Q = quality score; K = k-nearest neighbors; V = vocabulary",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: The Q/K/V analogy comes from database search: Query asks a question, Keys are the index of available information, Values are the content retrieved when a key matches.\n\nIntuition: Searching a library — your search query (Q) matches against book titles (K), and you retrieve the book content (V) proportional to how well each title matched.\n\nNote: Q, K, V are all learned linear projections of the same input — the model learns what to query and what to make available.",
            explanation: "Q, K, V are linear projections of the input. Attention weights = softmax(QK^T/√d_k) determine how much of each V to retrieve for each Q.",
            xpReward: 15,
          },
          {
            id: "l3-adv-m2-n1-e2",
            type: "fill-blank",
            question: "The self-attention formula is: Attention(Q,K,V) = softmax(QK^T / ___) · V\n\nFill in the scaling factor:",
            blanks: [
              { text: "square root of d_k", answer: "√d_k", position: 0 },
            ],
            hint: "🌌 TEACHING: Without scaling, large dot products push softmax into saturation (near 0/1), creating vanishing gradients.\n\nIntuition: Dividing by √d_k keeps the dot products at a reasonable scale regardless of embedding dimension — like normalizing scores on a test.\n\nNote: d_k is the dimension of the key vectors. In practice, each head uses d_model / n_heads dimensions.",
            explanation: "Scaling by √d_k prevents dot products from growing too large with dimension, keeping softmax in its gradient-rich regime.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n1-e3",
            type: "multiple-choice",
            question: "Why does self-attention allow each position to attend to all other positions simultaneously?",
            options: [
              "Because transformers process tokens one at a time like RNNs but faster",
              "Because the Q·K dot product is computed between every pair of positions in parallel, giving each token context from the entire sequence",
              "Because positional encodings store information about neighboring tokens",
              "Because attention masks force every token to look at all others",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Unlike RNNs that pass hidden states sequentially, attention computes all pairwise interactions in one matrix multiplication — O(n²) but fully parallel.\n\nIntuition: Instead of passing a note person-to-person down a row, everyone reads a shared whiteboard simultaneously.\n\nNote: This is why transformers are slower than RNNs for very long sequences (O(n²) attention) but train much faster in parallel on GPUs.",
            explanation: "The QK^T matrix multiplication computes dot products between all pairs of positions simultaneously, giving every token full-sequence context in one pass.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n1-e4",
            type: "multiple-choice",
            question: "What does the softmax operation do to the attention scores (QK^T/√d_k)?",
            options: [
              "Normalizes them to sum to 1, creating a probability distribution over positions",
              "Clips them to the range [-1, 1]",
              "Removes negative values using ReLU",
              "Averages them across the sequence length",
            ],
            correctIndex: 0,
            hint: "🌌 TEACHING: Softmax converts raw attention scores into a probability distribution — each token's attention is now a weighted combination of all positions summing to 1.\n\nIntuition: Voting — each position votes on which other positions are relevant, and the votes are normalized so they sum to 100%.\n\nNote: A peaked softmax (one high value) means the model focuses sharply on one position. A flat softmax means it attends broadly.",
            explanation: "Softmax(z_i) = exp(z_i) / Σ exp(z_j). The attention weights α_{ij} sum to 1 over j, creating a weighted average of V vectors.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n1-e5",
            type: "drag-drop",
            question: "Match the attention concept to what it enables in a protein language model:",
            pairs: [
              { left: "Token attending to nearby tokens", right: "Capturing local secondary structure (alpha-helix patterns)" },
              { left: "Token attending to distant tokens", right: "Capturing long-range contacts between residues far apart in sequence" },
              { left: "High attention weight between two positions", right: "Predicts a co-evolutionary constraint — these residues may be physically close in 3D" },
              { left: "Attention head specialization", right: "Different heads learn different structural relationships simultaneously" },
            ],
            hint: "🌌 TEACHING: In ESM and other protein language models, attention weights have been shown to capture structural contacts even without explicit structural training.\n\nIntuition: If two amino acids always mutate together across evolution, they likely interact physically — and attention can learn this pattern from sequence alone.\n\nNote: AlphaFold2 uses attention-like mechanisms in its Evoformer module to capture residue co-evolution.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n1-e6",
            type: "free-text",
            question: "A researcher wants to use a transformer to process a DNA sequence of 10,000 base pairs. The standard attention mechanism has O(n²) memory complexity. What is the memory cost for n=10,000, and why is this a problem? Name one approach to handle long sequences.",
            rubric: [
              "calculates or estimates 10,000² = 100 million attention score pairs",
              "explains memory/compute bottleneck for long sequences",
              "names a solution: Longformer, Linformer, sparse attention, chunked attention, or similar",
            ],
            hint: "🌌 TEACHING: 10,000² = 100M attention scores. At fp32, that's 400MB just for the attention matrix — per layer, per head.\n\nIntuition: It's like making a conversation transcript where every word responds to every other word. Manageable for a paragraph, impossible for a book.\n\nNote: Longformer uses sliding window + global attention; Hyena/Mamba uses state-space models to achieve O(n log n) or O(n) complexity.",
            xpReward: 35,
          },
        ],
      },
      {
        id: "l3-adv-m2-n2",
        moduleId: "l3-adv-m2",
        title: "Multi-Head Attention",
        description: "Parallel attention heads, concatenation, projection, and why multiple heads matter",
        icon: "🧠",
        xpReward: 240,
        exercises: [
          {
            id: "l3-adv-m2-n2-e1",
            type: "multiple-choice",
            question: "In multi-head attention with h=8 heads and d_model=512, what is the dimension of each head's Q, K, V projections?",
            options: [
              "512 — each head uses the full embedding dimension",
              "64 — each head gets d_model/h = 512/8 dimensions",
              "8 — one dimension per head",
              "4096 — the dimensions are expanded for each head",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Each head independently projects the input to a lower-dimensional space (d_model/h), so total computation stays the same as single-head attention.\n\nIntuition: Instead of one expert reviewing everything, you split the workload among 8 specialists each looking at a different aspect.\n\nNote: The key insight is that the total computation is the same — you just split it into h parallel smaller operations.",
            explanation: "Each head uses d_k = d_model/h = 64 dimensions. After h parallel attention operations, outputs are concatenated back to d_model=512.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n2-e2",
            type: "sequence-order",
            question: "Order the steps of multi-head attention:",
            items: [
              "Project input X into h separate Q, K, V matrices using learned weight matrices",
              "Compute scaled dot-product attention independently for each head",
              "Concatenate all h attention outputs along the feature dimension",
              "Apply a final linear projection W_O to produce the output",
            ],
            correctOrder: [0, 1, 2, 3],
            hint: "🌌 TEACHING: MultiHead(Q,K,V) = Concat(head_1,...,head_h) · W_O, where head_i = Attention(QW_i^Q, KW_i^K, VW_i^V).\n\nIntuition: Split → process in parallel → combine → project. Like having multiple reviewers each write a section, then an editor merges the sections into a coherent document.\n\nNote: The final projection W_O mixes information across heads, allowing them to interact.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n2-e3",
            type: "multiple-choice",
            question: "Why does using multiple attention heads improve over a single head?",
            options: [
              "Multiple heads increase the total number of parameters proportionally",
              "Each head can specialize in attending to different types of relationships (syntactic, semantic, positional) simultaneously",
              "Multiple heads prevent overfitting through implicit dropout",
              "Multi-head attention reduces computational complexity from O(n²) to O(n log n)",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Empirically, different heads in trained models learn different patterns — some attend to previous word, some to syntactic dependencies, some to semantic similarity.\n\nIntuition: A team of specialists each focusing on a different signal versus one generalist trying to attend to everything at once.\n\nNote: In protein models, some heads capture local backbone geometry, others capture long-range packing interactions.",
            explanation: "Each head learns distinct Q/K/V projections and therefore attends to different relationships. Concatenation lets the model leverage all simultaneously.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n2-e4",
            type: "drag-drop",
            question: "Match each component of a transformer block to its role:",
            pairs: [
              { left: "Multi-Head Self-Attention", right: "Allows each position to gather information from all other positions" },
              { left: "Feed-Forward Network (FFN)", right: "Applies position-wise non-linear transformation — acts as 'memory' for facts" },
              { left: "Layer Normalization", right: "Stabilizes training by normalizing activations; applied before or after each sublayer" },
              { left: "Residual Connection", right: "Adds the input directly to the sublayer output — prevents vanishing gradients in deep models" },
            ],
            hint: "🌌 TEACHING: The transformer block = self-attention (context gathering) + FFN (processing) + LayerNorm + residuals (stability).\n\nIntuition: Attention collects information from the room; FFN processes and stores it; LayerNorm keeps everyone on the same scale; residuals ensure nothing important is forgotten.\n\nNote: The FFN is typically 4× wider than d_model (e.g., 2048 for d_model=512) and is where most 'knowledge' is stored in large language models.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n2-e5",
            type: "multiple-choice",
            question: "In a transformer processing the amino acid sequence 'MGSSHHHHHHSSGLVPRGSH...', what role do positional encodings play?",
            options: [
              "They encode the amino acid identity (which of the 20 amino acids)",
              "They inject information about each position's location in the sequence, since attention is permutation-invariant",
              "They encode secondary structure predictions from a separate model",
              "They replace the need for attention masks",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Self-attention is order-agnostic — shuffling tokens doesn't change attention scores without positional encoding.\n\nIntuition: If you read a sentence and every word said 'word' without order, you'd have no idea what was said. Positional encoding adds sequence position information.\n\nNote: Protein language models like ESM-2 use learned positional embeddings; RoPE (Rotary Position Embedding) is now common for long sequences.",
            explanation: "Without positional encoding, attention treats the input as a bag of tokens. Positional encodings (sinusoidal or learned) let the model know where each token sits in the sequence.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n2-e6",
            type: "free-text",
            question: "ESM-2, a protein language model with 650M parameters, uses 33 transformer layers each with 20 attention heads. Describe what information you think different attention heads might specialize in when processing a protein sequence. How does this differ from what attention heads might learn in a text language model?",
            rubric: [
              "suggests biological examples like secondary structure, contact maps, or evolutionary patterns",
              "contrasts with linguistic patterns (syntactic dependencies, coreference) in text LMs",
              "notes that heads emerge from training without explicit biological supervision",
            ],
            hint: "🌌 TEACHING: Protein attention heads have been shown to capture backbone angles, contact maps, and conserved motifs — all emergent from next-token prediction on sequences.\n\nIntuition: The same attention mechanism learns grammar in text and structural contacts in proteins — the architecture is universal, the learned patterns are domain-specific.\n\nNote: Rao et al. (2020) showed that contacts between residues can be predicted from ESM attention maps with no structural training.",
            xpReward: 35,
          },
        ],
      },
      {
        id: "l3-adv-m2-n3",
        moduleId: "l3-adv-m2",
        title: "BERT vs GPT",
        description: "Encoder-only vs decoder-only, masked LM vs causal LM, and when to use each",
        icon: "🤖",
        xpReward: 240,
        exercises: [
          {
            id: "l3-adv-m2-n3-e1",
            type: "drag-drop",
            question: "Match each model type to its key property:",
            pairs: [
              { left: "BERT (encoder-only)", right: "Sees the entire sequence including future tokens — bidirectional context" },
              { left: "GPT (decoder-only)", right: "Sees only past tokens — autoregressive, predicts next token left to right" },
              { left: "T5 / BART (encoder-decoder)", right: "Encoder processes input; decoder generates output — ideal for seq2seq tasks" },
              { left: "ESM-2 (protein encoder)", right: "Masked language modeling on amino acid sequences — learns protein representations" },
            ],
            hint: "🌌 TEACHING: The fundamental difference: BERT reads the whole sequence at once (bidirectional); GPT reads left-to-right only (causal).\n\nIntuition: BERT reads a book and can see all pages. GPT reads the book one page at a time and must predict the next page without looking ahead.\n\nNote: Bidirectional context makes BERT better for understanding (classification, NER). Causal training makes GPT better for generation.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n3-e2",
            type: "multiple-choice",
            question: "BERT is pre-trained with Masked Language Modeling (MLM). What does this mean?",
            options: [
              "BERT masks the attention weights to prevent attending to padding tokens",
              "15% of input tokens are randomly masked; BERT learns to predict the original tokens from bidirectional context",
              "BERT masks future tokens to prevent information leakage during autoregressive generation",
              "BERT uses a binary mask to select which attention heads are active",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: MLM pre-training: [CLS] the [MASK] went to the [MASK] → predict 'cat' and 'store'. This forces BERT to understand context from both sides.\n\nIntuition: Fill-in-the-blank exercises — you need to understand the surrounding sentence to guess the missing word.\n\nNote: ESM uses the same MLM objective on protein sequences, randomly masking amino acids and training the model to predict them.",
            explanation: "MLM masks 15% of tokens and trains BERT to predict them using bidirectional context. This creates rich contextual representations but prevents generation.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n3-e3",
            type: "multiple-choice",
            question: "Why can't BERT be used directly for text generation (e.g., like ChatGPT)?",
            options: [
              "BERT has too many parameters for inference",
              "BERT's bidirectional attention means it cannot predict the next token autoregressively without seeing future tokens",
              "BERT was not trained on enough data",
              "BERT uses a different tokenizer that is incompatible with generation",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: BERT's encoder sees the full sequence in both directions — but generating text requires predicting the next token without future context.\n\nIntuition: You can't write a story if you already know how it ends every time you write a word.\n\nNote: BERT can be fine-tuned to classify or extract information from complete sequences, but GPT-style causal models are needed for generation.",
            explanation: "BERT's architecture uses bidirectional attention, which requires the full input at once. Generation requires predicting one token at a time from only past context.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n3-e4",
            type: "multiple-choice",
            question: "For predicting whether a patient's clinical notes describe sepsis risk (a classification task), which architecture is most appropriate?",
            options: [
              "GPT — because it can generate a 'yes' or 'no' token",
              "BERT — encode the full note with bidirectional context, add a classification head on the [CLS] token",
              "An encoder-decoder model — necessary for any classification task",
              "A decoder-only model with chain-of-thought prompting",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Classification needs understanding the full input — BERT's bidirectional context gives richer representations than GPT's left-only context.\n\nIntuition: To diagnose from a clinical note, you should read the whole note, not just up to each word.\n\nNote: BioClinicalBERT and ClinicalBERT are domain-specific versions fine-tuned on clinical text for exactly these tasks.",
            explanation: "BERT-style encoders are preferred for classification: they process the full sequence bidirectionally, then a linear head on [CLS] predicts the class.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n3-e5",
            type: "drag-drop",
            question: "Match each use case to the best model type:",
            pairs: [
              { left: "Generate a novel protein sequence with desired properties", right: "GPT-style decoder (ProtGPT2, ProGen)" },
              { left: "Predict protein function from sequence", right: "BERT-style encoder (ESM-2, ProtBERT)" },
              { left: "Translate a protein sequence to its predicted structure annotation", right: "Encoder-decoder (seq2seq)" },
              { left: "Answer questions about a patient's medical history", right: "GPT-style decoder (fine-tuned LLM)" },
            ],
            hint: "🌌 TEACHING: Encoder = understanding/classification. Decoder = generation. Encoder-decoder = transformation from one sequence to another.\n\nIntuition: Encoders read; decoders write; encoder-decoders translate.\n\nNote: Most modern LLMs (GPT-4, Claude, Gemini) are decoder-only but prompted cleverly to handle classification and extraction tasks.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m2-n3-e6",
            type: "free-text",
            question: "ESM-2 (a protein language model trained like BERT on amino acid sequences) achieves remarkable performance on structure prediction and functional annotation without ever seeing 3D coordinates during pre-training. Why can protein sequences alone encode enough information to predict structure?",
            rubric: [
              "references Anfinsen's dogma — sequence determines structure",
              "mentions co-evolutionary signals captured from millions of sequences",
              "explains that MLM forces the model to learn constraints on which amino acids can co-occur",
            ],
            hint: "🌌 TEACHING: Anfinsen's dogma (1972 Nobel Prize): a protein's sequence fully determines its 3D structure under physiological conditions.\n\nIntuition: The sequence is the blueprint. If you know the blueprint, you can predict the building — ESM learns these rules from patterns across millions of proteins.\n\nNote: Co-evolutionary signals (positions that mutate together) encode structural constraints — ESM picks these up through masked prediction across diverse sequences.",
            xpReward: 35,
          },
        ],
      },
    ],
  },
  {
    id: "l3-adv-m3",
    title: "ML Evaluation & Explainability",
    description: "Metrics, cross-validation, and understanding why models make decisions",
    realm: 3,
    color: "#a855f7",
    nodes: [
      {
        id: "l3-adv-m3-n1",
        moduleId: "l3-adv-m3",
        title: "Metrics Deep Dive",
        description: "Precision, recall, F1, ROC-AUC, PR curves — knowing which to trust",
        icon: "📊",
        xpReward: 230,
        exercises: [
          {
            id: "l3-adv-m3-n1-e1",
            type: "drag-drop",
            question: "Match each metric to its formula:",
            pairs: [
              { left: "Precision", right: "TP / (TP + FP) — of all predicted positives, how many are real?" },
              { left: "Recall (Sensitivity)", right: "TP / (TP + FN) — of all real positives, how many did we find?" },
              { left: "F1 Score", right: "2 · (Precision · Recall) / (Precision + Recall) — harmonic mean" },
              { left: "Specificity", right: "TN / (TN + FP) — of all real negatives, how many did we correctly identify?" },
            ],
            hint: "🌌 TEACHING: Precision = avoid false alarms. Recall = avoid missing cases. F1 balances both. Specificity = correctly identifying the healthy.\n\nIntuition: Cancer screening: Recall is 'did we catch every cancer?' Precision is 'are we sending only real cancer patients to surgery?'\n\nNote: In medical diagnostics, recall (sensitivity) for life-threatening diseases is often more important than precision.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n1-e2",
            type: "multiple-choice",
            question: "A sepsis detection model has 99% accuracy on a dataset where 1% of patients have sepsis. Why is accuracy misleading here?",
            options: [
              "Accuracy is always misleading for binary classification",
              "A model predicting 'no sepsis' for everyone achieves 99% accuracy — accuracy ignores the minority class",
              "The model must have used an incorrect loss function",
              "99% accuracy is too low for clinical use",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Class imbalance makes accuracy useless — predicting the majority class always wins.\n\nIntuition: A fire alarm that never goes off is '99% accurate' on normal days. That's not useful.\n\nNote: For imbalanced medical datasets, use AUC-ROC, F1, or precision-recall curve instead of accuracy.",
            explanation: "With 1% prevalence, always predicting negative gives 99% accuracy but 0% recall — every sepsis patient is missed. Use AUC or F1 instead.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n1-e3",
            type: "multiple-choice",
            question: "What does AUC-ROC measure?",
            options: [
              "The area under the precision-recall curve",
              "The probability that a randomly chosen positive example is ranked higher than a randomly chosen negative example",
              "The accuracy of the model at a fixed decision threshold",
              "The average loss across all thresholds",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: AUC = Area Under the ROC Curve. ROC plots True Positive Rate vs False Positive Rate at all thresholds. AUC=0.5 is random; AUC=1.0 is perfect.\n\nIntuition: If you pick a random cancer patient and a random healthy patient, AUC is the probability the model scores the cancer patient higher.\n\nNote: AUC is threshold-independent — it measures ranking quality, not just one operating point.",
            explanation: "AUC-ROC = P(score(positive) > score(negative)). It's the probability the model correctly ranks a positive example above a negative one.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n1-e4",
            type: "multiple-choice",
            question: "When is the Precision-Recall (PR) curve preferred over ROC-AUC?",
            options: [
              "Always — PR curves are always more informative than ROC",
              "When the dataset is highly imbalanced and you care about performance on the positive (minority) class",
              "When the model outputs probabilities rather than class labels",
              "When you have more than two classes",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: ROC can be overly optimistic when negatives vastly outnumber positives — the large TN pool inflates the FPR denominator.\n\nIntuition: If 99% of patients are healthy, even a mediocre model looks great on ROC because it's easy to get most negatives right.\n\nNote: For rare disease detection or fraud detection, PR-AUC is the standard — it focuses entirely on the minority positive class.",
            explanation: "PR curves focus on precision and recall — both are calculated from TP, FP, FN without using TN. This is better for imbalanced datasets where TN dominates.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n1-e5",
            type: "multiple-choice",
            question: "A drug discovery model predicts whether a compound will be active against a cancer target. In clinical development, a false negative (missing a real active compound) costs millions in lost opportunity. A false positive (testing an inactive compound) costs $50,000 in lab testing. What metric should you optimize?",
            options: [
              "Specificity — minimize false positives to save testing costs",
              "Recall — do not miss real active compounds even if it means testing more false positives",
              "F1 — balance precision and recall equally",
              "Accuracy — maximize overall correct predictions",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: When the cost of false negatives >> cost of false positives, optimize recall even at the expense of precision.\n\nIntuition: At early-stage drug screening with millions of potential compounds, you can afford to test some inactive ones — you cannot afford to discard the next blockbuster drug.\n\nNote: As you progress to clinical trials, the calculus reverses — false positives in Phase III trials cost $100M+.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n1-e6",
            type: "free-text",
            question: "A genomics startup claims their variant pathogenicity classifier has 'industry-leading performance' with 95% accuracy and AUC=0.82. You notice their test set has 5% pathogenic variants and 95% benign. What additional metrics would you demand before trusting this claim, and why?",
            rubric: [
              "requests precision and recall separately (not just F1)",
              "notes the imbalanced test set undermines accuracy",
              "asks for performance stratified by variant type or clinical significance tier",
            ],
            hint: "🌌 TEACHING: Always demand stratified metrics and the confusion matrix on real-world prevalence data — aggregate metrics hide clinical failure modes.\n\nIntuition: Average performance can hide that the model fails catastrophically on the most important rare variant classes.\n\nNote: ClinVar has massive class imbalance. Models claiming 95%+ accuracy are often just predicting 'benign' for most variants.",
            xpReward: 35,
          },
        ],
      },
      {
        id: "l3-adv-m3-n2",
        moduleId: "l3-adv-m3",
        title: "Cross-Validation",
        description: "k-fold, stratified k-fold, time-series CV, and why we split data",
        icon: "🔄",
        xpReward: 220,
        exercises: [
          {
            id: "l3-adv-m3-n2-e1",
            type: "multiple-choice",
            question: "In k-fold cross-validation with k=5, how is the data used?",
            options: [
              "5% of data is used for validation; 95% for training",
              "Data is split into 5 equal folds; each fold serves as validation once while the rest train — producing 5 models and 5 validation scores",
              "Data is split randomly 5 times into 80/20 splits and averaged",
              "The model is trained 5 times on the same data with different random seeds",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: k-fold ensures every data point is used for validation exactly once — more reliable than a single train/val split, especially with small datasets.\n\nIntuition: Rotating which students are the 'test group' in a class study — everyone gets evaluated, and you average the scores.\n\nNote: k=5 or k=10 are most common. Higher k = less bias but more computation.",
            explanation: "5-fold CV creates 5 (train=80%, val=20%) splits. Each fold is the validation set once. Final performance = mean ± std of 5 validation scores.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n2-e2",
            type: "multiple-choice",
            question: "Why is stratified k-fold preferred over regular k-fold for imbalanced datasets?",
            options: [
              "Stratified k-fold is always faster than regular k-fold",
              "Stratified k-fold ensures each fold has the same class proportions as the full dataset",
              "Stratified k-fold prevents data leakage between folds",
              "Stratified k-fold uses more data for training",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: With 5% positives, random splitting might give a fold with 0% positives — making that fold's evaluation meaningless.\n\nIntuition: If you're dividing a bag of M&Ms evenly among friends, stratified = each friend gets the same color ratio, not random handfuls.\n\nNote: Sklearn's StratifiedKFold preserves class proportions; for regression, use KFold or stratify by binned target values.",
            explanation: "Stratification ensures each fold reflects the true class distribution, preventing folds with zero or very few positive examples.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n2-e3",
            type: "multiple-choice",
            question: "You're building a model to predict patient deterioration using hourly vital signs. You split data with standard k-fold. What critical problem does this create?",
            options: [
              "k-fold requires too much memory for time-series data",
              "Future data (hour 24 vitals) leaks into training, letting the model 'see the future' — producing impossibly optimistic results",
              "k-fold cannot handle missing values common in ICU data",
              "The class imbalance is worse with k-fold for time-series",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Temporal data requires time-series CV: train on past, validate on future. Never let future data appear in the training fold.\n\nIntuition: Predicting tomorrow's stock price using tomorrow's news in your training set — your model memorizes the future.\n\nNote: Use sklearn's TimeSeriesSplit, which always trains on past and validates on the next time window.",
            explanation: "Standard k-fold randomly shuffles data, mixing future and past. For time-series, always train on earlier time points and validate on later ones.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n2-e4",
            type: "drag-drop",
            question: "Match each CV strategy to its correct use case:",
            pairs: [
              { left: "Standard k-fold", right: "Tabular patient data with independent observations" },
              { left: "Stratified k-fold", right: "Imbalanced dataset (e.g., rare disease classification)" },
              { left: "Time-Series Split", right: "Sequential data where future must not leak into training (EHR, wearables)" },
              { left: "Group k-fold", right: "Multiple samples per patient — keep one patient's samples in the same fold" },
            ],
            hint: "🌌 TEACHING: Group k-fold is critical in genomics when you have multiple samples from the same patient or cell line — data leakage by sample identity.\n\nIntuition: If patient A has 10 tumor samples and one is in test, information about patient A leaks from the other 9 in train.\n\nNote: This is a widespread problem in single-cell RNA-seq ML papers — many inflate performance by not splitting by donor.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n2-e5",
            type: "multiple-choice",
            question: "What is 'data leakage' in ML, and why is it dangerous in clinical studies?",
            options: [
              "When training data is accidentally shared publicly",
              "When information from the test set (or future data) influences the model during training, leading to inflated performance estimates",
              "When patient data is not properly anonymized",
              "When the model memorizes training examples verbatim",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Data leakage is arguably the most common source of irreproducible ML results in clinical and genomics papers.\n\nIntuition: Giving students the answers before a test — scores look great, but you've learned nothing about who actually understands the material.\n\nNote: Common forms: normalizing with test set statistics, feature selection before splitting, temporal leakage in EHR studies.",
            explanation: "Leakage occurs when test information influences training — e.g., fitting a scaler on all data before splitting. Models appear accurate but fail when deployed.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n2-e6",
            type: "free-text",
            question: "A paper claims a genomics model achieves AUC=0.97 using 5-fold cross-validation on 200 patient samples with 50 positive cases. They also report 500 features selected from the full dataset before splitting. What is wrong with this validation strategy, and how would you fix it?",
            rubric: [
              "identifies feature selection on full data before splitting as leakage",
              "explains that features selected using test fold statistics inflate performance",
              "suggests nested CV or performing feature selection inside each training fold",
            ],
            hint: "🌌 TEACHING: Feature selection uses statistical properties of each sample — selecting on the full dataset lets test-set statistics influence which features are chosen.\n\nIntuition: Grading an essay by first reading all essays (including the test ones), then deciding what good essays look like — and then grading.\n\nNote: Correct approach: for each CV fold, run feature selection on the training fold only, then apply those features to the validation fold.",
            xpReward: 35,
          },
        ],
      },
      {
        id: "l3-adv-m3-n3",
        moduleId: "l3-adv-m3",
        title: "Explainable AI",
        description: "SHAP, LIME, attention visualization, and why XAI matters in medicine",
        icon: "💡",
        xpReward: 240,
        exercises: [
          {
            id: "l3-adv-m3-n3-e1",
            type: "multiple-choice",
            question: "What do SHAP (SHapley Additive exPlanations) values measure?",
            options: [
              "The model's overall accuracy on the test set",
              "The contribution of each feature to a specific prediction — how much each feature shifted the output from the average prediction",
              "The correlation between each feature and the target variable",
              "The probability that each feature causes the outcome",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: SHAP values come from cooperative game theory — each feature gets 'credit' for its contribution averaged across all possible feature coalitions.\n\nIntuition: In a team project, SHAP measures how much each person contributed by averaging their impact across all possible team combinations.\n\nNote: SHAP values sum to the difference between the specific prediction and the average prediction, making them completely additive.",
            explanation: "SHAP value for feature i in prediction j = how much feature i changed the prediction from the base rate. Sum of all SHAP values = prediction - mean prediction.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n3-e2",
            type: "multiple-choice",
            question: "LIME (Local Interpretable Model-agnostic Explanations) explains predictions by:",
            options: [
              "Retraining the model with fewer features until it becomes interpretable",
              "Fitting a simple interpretable model (linear/decision tree) to explain the original model's behavior in the local neighborhood of a specific prediction",
              "Computing gradient magnitudes with respect to each input feature",
              "Removing features one at a time and observing the change in prediction",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: LIME creates perturbations around a specific data point and fits a simple model to approximate the black box's behavior locally.\n\nIntuition: You can't understand the whole globe's geography at once, but you can map the neighborhood around a specific city — LIME does this for predictions.\n\nNote: 'Local' is the key word — LIME explanations only describe behavior near one specific prediction, not the model globally.",
            explanation: "LIME perturbs the input, gets the black-box model's predictions on perturbations, then fits an interpretable model locally. This is model-agnostic — works on any classifier.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n3-e3",
            type: "drag-drop",
            question: "Match each XAI method to its key property:",
            pairs: [
              { left: "SHAP", right: "Theoretically grounded in game theory; globally consistent feature importance" },
              { left: "LIME", right: "Model-agnostic; local approximation; fast but can be unstable" },
              { left: "Attention Visualization", right: "Shows which tokens a transformer attended to — but attention ≠ causation" },
              { left: "Integrated Gradients", right: "Gradient-based; attributes prediction to input features by integrating along a path" },
            ],
            hint: "🌌 TEACHING: No single XAI method is universally best — each has tradeoffs in theoretical guarantees, computational cost, and interpretability.\n\nIntuition: Like different kinds of maps (topographic, political, satellite) — each reveals different truths about the same territory.\n\nNote: Attention visualization is tempting in transformers but researchers have shown attention weights don't reliably indicate causal importance.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n3-e4",
            type: "multiple-choice",
            question: "A pathology AI model correctly diagnoses melanoma but SHAP analysis reveals it's primarily using the ruler artifact (scale bar) in images, not the actual tumor features. What ML problem does this illustrate?",
            options: [
              "Overfitting — the model has too many parameters",
              "Shortcut learning (Clever Hans effect) — the model learns spurious correlations rather than causal features",
              "Data leakage — test images appeared in training",
              "Label noise — some melanoma images were incorrectly labeled",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: Shortcut learning: the model finds predictive but spurious features (rulers appear more in dermatologist-photographed lesions). High accuracy but zero clinical reliability.\n\nIntuition: The 'Clever Hans' horse appeared to solve math by reading audience cues — it learned the right answer for the wrong reason.\n\nNote: This exact finding appeared in real dermatology AI papers — rulers were confounded with clinical lesions requiring photography.",
            explanation: "Shortcut learning (Clever Hans) = high performance via spurious correlations not causal features. XAI reveals this and is essential for clinical deployment.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n3-e5",
            type: "multiple-choice",
            question: "Why is XAI particularly important in clinical medicine compared to, say, a movie recommendation system?",
            options: [
              "Clinical models are always more accurate and need more scrutiny",
              "Clinical decisions have life-or-death consequences, face regulatory requirements, need clinician trust, and require understanding failure modes",
              "Clinical data is always more complex than consumer data",
              "Hospital IT systems cannot deploy black-box models",
            ],
            correctIndex: 1,
            hint: "🌌 TEACHING: The FDA's AI/ML framework and EU AI Act classify clinical AI as 'high-risk' requiring human oversight, documentation, and explainability.\n\nIntuition: A black-box recommendation for a movie is low stakes. A black-box treatment recommendation affects patient survival — clinicians need to know why.\n\nNote: Clinical XAI also aids debugging: if a model says 'high sepsis risk' because the patient was admitted on a Tuesday, something is wrong.",
            explanation: "Clinical AI failure modes can harm patients. Explainability enables clinician oversight, regulatory compliance, error detection, and appropriate trust calibration.",
            xpReward: 20,
          },
          {
            id: "l3-adv-m3-n3-e6",
            type: "free-text",
            question: "You train a gene expression model to predict cancer prognosis and use SHAP to identify the top 10 most important genes. A clinical collaborator asks whether these genes are 'causing' the prognosis or just 'correlated' with it. How do you explain the difference, and what additional study design would be needed to make a causal claim?",
            rubric: [
              "clearly distinguishes correlation from causation in SHAP outputs",
              "explains SHAP measures predictive importance, not causal effect",
              "suggests a causal framework: RCT, Mendelian randomization, or perturbation experiments",
            ],
            hint: "🌌 TEACHING: SHAP measures how much a feature changes the model's prediction — but correlation in observational data ≠ causal effect.\n\nIntuition: Ice cream sales predict drowning rates (both rise in summer). SHAP would highlight ice cream as important — but banning ice cream won't reduce drowning.\n\nNote: Causal inference requires intervention: randomized trials, CRISPR knockouts, or Mendelian randomization using genetic variants as natural experiments.",
            xpReward: 35,
          },
        ],
      },
    ],
  },
];

export default level3AdvancedModules;
