import type { MascotDialogue } from "@/lib/types";

export const alexDialogue: MascotDialogue[] = [
  {
    id: "a-welcome-1",
    trigger: "welcome",
    tone: "neutral",
    text: "Machine learning is not magic. It is very sophisticated curve fitting. I say this with complete respect and also to manage your expectations.",
    animation: "idle",
  },
  {
    id: "a-welcome-2",
    trigger: "welcome",
    tone: "neutral",
    text: "Welcome to Level 3. I'll be direct: this is harder. Not impossible — clearly, since you're here — but it requires you to think precisely. Let's begin.",
    animation: "wave",
  },
  {
    id: "a-correct-1",
    trigger: "correct",
    tone: "proud",
    text: "Perfect. You understand backpropagation. I'm giving you a metaphorical gold star. In PyTorch this would've taken me another hour to explain because the— anyway. Gold star.",
    animation: "cheer",
  },
  {
    id: "a-correct-2",
    trigger: "correct",
    tone: "encouraging",
    text: "Correct. The loss is going down. That's the direction we want. This is not a coincidence — this is calculus working exactly as intended.",
    animation: "cheer",
  },
  {
    id: "a-correct-3",
    trigger: "correct",
    tone: "proud",
    text: "Yes. Precisely. That's the answer and also the reason, which is even better than just the answer. I appreciate thoroughness.",
    animation: "jump",
  },
  {
    id: "a-correct-4",
    trigger: "correct",
    tone: "funny",
    text: "Right. And that is why I left the startup. They didn't understand gradient descent either. Well — that, and they pivoted to snacks.",
    animation: "cheer",
  },
  {
    id: "a-wrong-1",
    trigger: "wrong",
    tone: "neutral",
    text: "The loss is going up. That's not ideal. But it's also data. What is the data telling you? Incorrect answers are just gradients pointing a different direction.",
    animation: "think",
  },
  {
    id: "a-wrong-2",
    trigger: "wrong",
    tone: "encouraging",
    text: "Not quite. Fun fact: I once trained a model for three days and it learned to output the mean of the training set for every input. Technically not wrong. Deeply wrong. We recover.",
    animation: "sad",
  },
  {
    id: "a-wrong-3",
    trigger: "wrong",
    tone: "encouraging",
    text: "Incorrect — but the error is useful. Think about the gradient. Where does it want to push you? Which direction reduces the loss?",
    animation: "think",
  },
  {
    id: "a-lesson-start-1",
    trigger: "lesson-start",
    tone: "neutral",
    text: "I've had six espressos today. I am aware this is too many. I am also very focused. Let's use this energy productively.",
    animation: "idle",
  },
  {
    id: "a-lesson-start-2",
    trigger: "lesson-start",
    tone: "excited",
    text: "This module is genuinely interesting — I say that rarely. The mathematics here are elegant in a way that the PyTorch documentation does not adequately convey. Let me show you.",
    animation: "jump",
  },
  {
    id: "a-lesson-complete-1",
    trigger: "lesson-complete",
    tone: "proud",
    text: "Excellent work. I mean that technically: the work was excellent. You understood the objective, minimized your error, and converged to the correct answer. That is literally ML.",
    animation: "cheer",
  },
  {
    id: "a-lesson-complete-2",
    trigger: "lesson-complete",
    tone: "excited",
    text: "Done. And well done. The nebula just added another layer to the network in your honor. Metaphorically. But also look — it actually did.",
    animation: "spin",
  },
  {
    id: "a-streak-1",
    trigger: "streak",
    tone: "neutral",
    text: "Day streak logged. Consistency is a hyperparameter most people don't tune. You're tuning it correctly.",
    animation: "cheer",
  },
  {
    id: "a-streak-2",
    trigger: "streak",
    tone: "proud",
    text: "I've been tracking your streak on a chart. The trend is statistically significant at p < 0.01. Keep going.",
    animation: "idle",
  },
  {
    id: "a-idle-1",
    trigger: "idle",
    tone: "funny",
    text: "I once ran a model for 72 hours that produced NaN loss at epoch 73. I don't talk about it. I'm talking about it right now but this is not a pattern.",
    animation: "think",
  },
  {
    id: "a-idle-2",
    trigger: "idle",
    tone: "neutral",
    text: "The company I used to work at is now a snack company. They make pretzels. The pretzels are good. This does not change how I feel.",
    animation: "idle",
  },
  {
    id: "a-idle-3",
    trigger: "idle",
    tone: "funny",
    text: "Coffee number seven. I see you judging me. The optimal learning rate for caffeine has not been formally studied. I am collecting data.",
    animation: "idle",
  },
  {
    id: "a-hint-1",
    trigger: "hint",
    tone: "neutral",
    text: "Think about the loss function. What is it trying to minimize? Start there — the answer follows from the objective.",
    animation: "think",
  },
  {
    id: "a-hint-2",
    trigger: "hint",
    tone: "encouraging",
    text: "Hint: break this into smaller parts. What do you know for certain? What are you unsure about? Handle certainty first.",
    animation: "think",
  },
];
