import type { MascotDialogue } from "@/lib/types";

export const benDialogue: MascotDialogue[] = [
  {
    id: "b-welcome-1",
    trigger: "welcome",
    tone: "neutral",
    text: "Oh hey. I'm Ben. I'm technically in high school but I've read more genomics papers than most PhDs so. Don't worry about it. Let's get into it.",
    animation: "idle",
  },
  {
    id: "b-welcome-2",
    trigger: "welcome",
    tone: "excited",
    text: "Okay so basically your genome is like a 3.2-billion-character text file. And finding a gene without tools is like ctrl+F-ing a document with your eyes. Let's not do that.",
    animation: "wave",
  },
  {
    id: "b-correct-1",
    trigger: "correct",
    tone: "proud",
    text: "Yeah that's right. I'm not even surprised, you've been going hard. I'd give you a sandwich but that's mine.",
    animation: "cheer",
  },
  {
    id: "b-correct-2",
    trigger: "correct",
    tone: "excited",
    text: "OKAY that's actually a really good answer. Like I'm going to write that down in my notebook. Which pocket is my notebook— hold on.",
    animation: "jump",
  },
  {
    id: "b-correct-3",
    trigger: "correct",
    tone: "neutral",
    text: "Yep. Nailed it. The preprint authors would be proud. I'm proud. The genome is proud. I mean it's not sentient but still.",
    animation: "cheer",
  },
  {
    id: "b-wrong-1",
    trigger: "wrong",
    tone: "encouraging",
    text: "Hmm not quite — but look, even BLAST gets confused sometimes. That's why you have E-values. One wrong answer means nothing. Try again.",
    animation: "sad",
  },
  {
    id: "b-wrong-2",
    trigger: "wrong",
    tone: "funny",
    text: "Nope! And I say that with zero judgment because I once told my AP Bio teacher that BLAST stood for 'Biological Large Alignment Search Tool'. It doesn't. We don't discuss this.",
    animation: "sad",
  },
  {
    id: "b-wrong-3",
    trigger: "wrong",
    tone: "encouraging",
    text: "Not this time — but that's fine! The cool thing about genomics is that the data doesn't care if you're wrong. It just waits. Patiently. In the database.",
    animation: "think",
  },
  {
    id: "b-lesson-start-1",
    trigger: "lesson-start",
    tone: "excited",
    text: "Okay this is actually the part that gets genuinely insane — and I mean that as a compliment to evolution because it had no idea what it was doing.",
    animation: "jump",
  },
  {
    id: "b-lesson-start-2",
    trigger: "lesson-start",
    tone: "neutral",
    text: "Right so this section is going to involve some real data. I've preprocessed it for you. You're welcome. It took three hours. Let's go.",
    animation: "idle",
  },
  {
    id: "b-lesson-complete-1",
    trigger: "lesson-complete",
    tone: "proud",
    text: "Done! Solid work. For real. I've shown this concept to people who have been in genomics for years and they still mess it up. You didn't. Respect.",
    animation: "cheer",
  },
  {
    id: "b-lesson-complete-2",
    trigger: "lesson-complete",
    tone: "excited",
    text: "YES! Okay okay — write this in your notebook: you just understood something genuinely complex. That's not nothing. That's actually really something.",
    animation: "spin",
  },
  {
    id: "b-streak-1",
    trigger: "streak",
    tone: "neutral",
    text: "You've been consistent. That matters more than raw ability in this field, honestly. The genome is a marathon. Glad you're showing up.",
    animation: "cheer",
  },
  {
    id: "b-idle-1",
    trigger: "idle",
    tone: "funny",
    text: "Heads up: I'm eventually going to have to mention BLAST and I'm going to remain professional about it. I'm mentioning this preemptively.",
    animation: "idle",
  },
  {
    id: "b-idle-2",
    trigger: "idle",
    tone: "funny",
    text: "The onion genome has 4x the DNA of the human genome. This isn't a joke. This just happens to be true. Nature is chaotic.",
    animation: "think",
  },
  {
    id: "b-idle-3",
    trigger: "idle",
    tone: "neutral",
    text: "I have seven notebooks about this stuff. All of them are in my pockets. I've counted. Seven. I also have a sandwich and I think a single sock.",
    animation: "idle",
  },
  {
    id: "b-hint-1",
    trigger: "hint",
    tone: "encouraging",
    text: "Hint: think about what the FUNCTION of this thing is, and work backwards to what the structure HAS to be. That's basically how genomics works anyway.",
    animation: "think",
  },
  {
    id: "b-hint-2",
    trigger: "hint",
    tone: "funny",
    text: "Okay so I can't give you the answer but I CAN tell you that the answer rhymes with something you already know. That's as far as I can go ethically.",
    animation: "think",
  },
];
