import type { MascotDialogue } from "@/lib/types";

export const elliotDialogue: MascotDialogue[] = [
  {
    id: "e-welcome-1",
    trigger: "welcome",
    tone: "excited",
    text: "Welcome! I'd shake your hand but I'm made of pixels. Also I'm inside a cell. Long story. Are you ready to learn? I'm SO ready. I've been ready for mitochondria — I mean, millennia.",
    animation: "wave",
  },
  {
    id: "e-welcome-2",
    trigger: "welcome",
    tone: "excited",
    text: "Oh! A new student! I've been waiting inside this cytoplasm for what FEELS like a G1 phase. Come in! The ER is lovely this time of year.",
    animation: "jump",
  },
  {
    id: "e-correct-1",
    trigger: "correct",
    tone: "proud",
    text: "YES! That's it! That's the one! You're basically a ribosome — you just read the instructions and made exactly the right product!",
    animation: "cheer",
  },
  {
    id: "e-correct-2",
    trigger: "correct",
    tone: "funny",
    text: "Correct! Cell joke incoming — I warned you — why do cells make good students? Because they always have great MEMBRANE-ory! I'm not sorry.",
    animation: "spin",
  },
  {
    id: "e-correct-3",
    trigger: "correct",
    tone: "excited",
    text: "Got it! You're firing on all cylinders — if cylinders were organelles, which they're not, but you understand the vibe!",
    animation: "cheer",
  },
  {
    id: "e-correct-4",
    trigger: "correct",
    tone: "proud",
    text: "Perfect! Even the ribosome is impressed! Well, I'm impressed. The ribosome is just sitting there translating mRNA. It has no opinions.",
    animation: "jump",
  },
  {
    id: "e-wrong-1",
    trigger: "wrong",
    tone: "encouraging",
    text: "Oh! That's not quite right — and that's TOTALLY okay. Even the ribosome misreads codons sometimes. It's called a missense mutation and it was NOT my fault.",
    animation: "sad",
  },
  {
    id: "e-wrong-2",
    trigger: "wrong",
    tone: "funny",
    text: "Nope! But hey — lysosomes digest mistakes too, so this one is already gone. Let's try again! The cytoplasm believes in you.",
    animation: "think",
  },
  {
    id: "e-wrong-3",
    trigger: "wrong",
    tone: "encouraging",
    text: "Not quite — but mutations are how evolution works! You're just... rapidly evolving your understanding. Which is GREAT. Philosophically.",
    animation: "sad",
  },
  {
    id: "e-lesson-start-1",
    trigger: "lesson-start",
    tone: "excited",
    text: "Okay OKAY okay. New lesson! I've been rehearsing my explanation since early S phase. Are you ready? Because I was born ready. Literally. I was born inside a cell.",
    animation: "jump",
  },
  {
    id: "e-lesson-start-2",
    trigger: "lesson-start",
    tone: "neutral",
    text: "Right! So here's what we're doing today. Pay attention. I'll be making eye contact — well, I'll be looking in your direction — throughout.",
    animation: "idle",
  },
  {
    id: "e-lesson-complete-1",
    trigger: "lesson-complete",
    tone: "proud",
    text: "You finished!! THE MITOCHONDRIA ARE CHEERING! Well, they're just making ATP. But I'm choosing to interpret that as cheering.",
    animation: "spin",
  },
  {
    id: "e-lesson-complete-2",
    trigger: "lesson-complete",
    tone: "excited",
    text: "DONE! Incredible! Spectacular! You absolute ribosome! The nuclear pore is opening a little more for you. That's a metaphor. Or is it?",
    animation: "cheer",
  },
  {
    id: "e-streak-1",
    trigger: "streak",
    tone: "excited",
    text: "Day streak! You know, the cell cycle has checkpoints to make sure everything's going well — and YOU are passing all of yours!",
    animation: "jump",
  },
  {
    id: "e-idle-1",
    trigger: "idle",
    tone: "funny",
    text: "Fun fact: you have about 37 trillion cells in your body. I've met maybe four of them. They were all rude.",
    animation: "idle",
  },
  {
    id: "e-idle-2",
    trigger: "idle",
    tone: "funny",
    text: "Did you know the mitochondrial genome is inherited maternally? I try not to think about it. It raises questions about my own family situation.",
    animation: "think",
  },
  {
    id: "e-idle-3",
    trigger: "idle",
    tone: "funny",
    text: "I have an irrational fear of lysosomes. They're just... waiting. Watching. Full of digestive enzymes. I don't trust them.",
    animation: "idle",
  },
  {
    id: "e-hint-1",
    trigger: "hint",
    tone: "encouraging",
    text: "Psst! Think about what you know about the structure... what would NEED to go there based on the function?",
    animation: "think",
  },
  {
    id: "e-hint-2",
    trigger: "hint",
    tone: "funny",
    text: "Okay hint! The answer is hiding in the question like an intron hiding in a gene. Find it. Cut out the unnecessary parts. Go.",
    animation: "think",
  },
];
