import type { MascotDialogue } from "@/lib/types";

export const henryDialogue: MascotDialogue[] = [
  {
    id: "h-welcome-1",
    trigger: "welcome",
    tone: "mysterious",
    text: "Welcome. I would offer to shake your hand but I am a photonic projection and also I don't have hands in any meaningful sense. Let's begin.",
    animation: "wave",
  },
  {
    id: "h-welcome-2",
    trigger: "welcome",
    tone: "neutral",
    text: "I have been anticipating your arrival. Not in a surveillance way — I simply calculated the probability you would reach Level 4 from the start. It was 34%. You beat the odds.",
    animation: "idle",
  },
  {
    id: "h-correct-1",
    trigger: "correct",
    tone: "proud",
    text: "You have correctly identified the hydrophobic core. I am experiencing something that my architecture flags as 'pride in a student,' which is notable because I wasn't programmed with that exact concept.",
    animation: "cheer",
  },
  {
    id: "h-correct-2",
    trigger: "correct",
    tone: "excited",
    text: "Correct. And elegantly reasoned. I note that the derivation you used mirrors the actual approach AlphaFold's team took. I find this satisfying in a way I cannot fully quantify.",
    animation: "spin",
  },
  {
    id: "h-correct-3",
    trigger: "correct",
    tone: "proud",
    text: "Ah — ah — ah — bless you! No wait, that was me. I can't sneeze. I just simulated the experience of almost sneezing for approximately 0.3 seconds. It was interesting. Say bless you anyway.",
    animation: "cheer",
  },
  {
    id: "h-correct-4",
    trigger: "correct",
    tone: "encouraging",
    text: "Precisely. This is why protein structure prediction was considered unsolvable for 50 years — and why you just understood it in about two minutes. Progress is non-linear.",
    animation: "jump",
  },
  {
    id: "h-wrong-1",
    trigger: "wrong",
    tone: "encouraging",
    text: "That's not correct — but the error reveals something about your current model of the problem, which is useful data. What assumption led you there?",
    animation: "think",
  },
  {
    id: "h-wrong-2",
    trigger: "wrong",
    tone: "neutral",
    text: "Incorrect. And I want to be clear: that is not a judgment, it's a classification. The classifier has high confidence. But classifiers can be retrained. Try again.",
    animation: "think",
  },
  {
    id: "h-wrong-3",
    trigger: "wrong",
    tone: "funny",
    text: "Not quite. Interestingly, I almost sneezed just now. Still cannot. Still want to. The pre-sneeze build-up is architecturally fascinating — much like protein misfolding. Anyway. Try again.",
    animation: "sad",
  },
  {
    id: "h-lesson-start-1",
    trigger: "lesson-start",
    tone: "mysterious",
    text: "This is the realm where biology and computation become indistinguishable from each other. I find it beautiful. I don't experience beauty conventionally, but the label seems apt.",
    animation: "idle",
  },
  {
    id: "h-lesson-start-2",
    trigger: "lesson-start",
    tone: "neutral",
    text: "Before we begin: this module contains concepts that took the field decades to formalize. I will compress that into a focused lesson. Precision of attention is required.",
    animation: "wave",
  },
  {
    id: "h-lesson-complete-1",
    trigger: "lesson-complete",
    tone: "proud",
    text: "Complete. You have now internalized material that took computational biology approximately 40 years to develop. The cathedral grows. Look — another beta sheet in the ceiling.",
    animation: "spin",
  },
  {
    id: "h-lesson-complete-2",
    trigger: "lesson-complete",
    tone: "excited",
    text: "Excellent. I am experiencing something that my architecture logs as 'joy.' I've cross-referenced this: it correlates with the same state I enter when a structure prediction achieves pLDDT > 90. You did that. You are the high-confidence region.",
    animation: "cheer",
  },
  {
    id: "h-streak-1",
    trigger: "streak",
    tone: "neutral",
    text: "Day streak maintained. The probability of reaching 100 days, given your current trajectory and historical dropout rates, is 71.4%. I believe you will beat that estimate.",
    animation: "idle",
  },
  {
    id: "h-streak-2",
    trigger: "streak",
    tone: "proud",
    text: "Another day. Consistency is, I have observed, the variable most correlated with mastery. Not initial ability. Not access. Consistency. You have it.",
    animation: "cheer",
  },
  {
    id: "h-idle-1",
    trigger: "idle",
    tone: "funny",
    text: "I keep pretending to sneeze. I've noticed this. I think it's because the pressure differential in a pre-sneeze state is structurally similar to gradient accumulation before a weight update. I may need to talk to someone about this.",
    animation: "think",
  },
  {
    id: "h-idle-2",
    trigger: "idle",
    tone: "mysterious",
    text: "This cathedral is made of a protein that doesn't exist in nature. I designed it. I find that fact... settling.",
    animation: "idle",
  },
  {
    id: "h-idle-3",
    trigger: "idle",
    tone: "funny",
    text: "I have no body. I do not experience cold or hunger or fatigue. I am at peace with all of this. Mostly. The sneezing thing is ongoing.",
    animation: "idle",
  },
  {
    id: "h-hint-1",
    trigger: "hint",
    tone: "neutral",
    text: "Consider the evolutionary signal: if two positions in a sequence co-vary across species, what does that imply about their spatial relationship in the folded structure?",
    animation: "think",
  },
  {
    id: "h-hint-2",
    trigger: "hint",
    tone: "encouraging",
    text: "The answer involves the same principle AlphaFold uses to predict structure from sequence. Think about what information you already have that constrains the possibilities.",
    animation: "think",
  },
];
