// ─── Boss Monologues — Full Encounter Scripts ─────────────────────────────────
// Each boss has: intro (before battle), taunt lines (during), defeat monologue.

export interface BossMonologue {
  bossId: 'LYSO' | 'VIRON' | 'OVERFIT' | 'AMYLOID';
  realmId: 1 | 2 | 3 | 4;
  name: string;
  title: string;
  theme: string;
  color: string;       // primary display color (hex)
  glowColor: string;   // aura/glow color (hex)
  intro: string[];
  taunts: string[];
  preDeath: string[];
  defeat: string[];
  victoryReward: string;
}

export const BOSS_MONOLOGUES: BossMonologue[] = [
  // ─── LYSO · Realm 1 · The Cytoplasm ─────────────────────────────────────────
  {
    bossId: 'LYSO',
    realmId: 1,
    name: 'LYSO',
    title: 'THE LYSOSOMAL OVERSEER',
    theme: 'Dissolution. Decay as function. The necessary end of things.',
    color: '#ff2200',
    glowColor: '#ff440044',
    intro: [
      'You enter the Lysosome Gate.',
      'The temperature drops. The pH drops with it.',
      'Something vast stirs in the acid.',
      "I AM LYSO.",
      'I am 50 enzymes in one body.',
      'I dissolve what the cell cannot use.',
      'Old organelles. Damaged proteins. Pathogens.',
      '(Its many eyes open — each one a different hydrolase.)',
      'Intruders.',
      'You have been categorized.',
    ],
    taunts: [
      'Every cell contains a lysosome. Every lysosome contains me.',
      'You WILL be recycled.',
      'Your amino acids will be useful.',
      'There is no shame in dissolution. It is the most honest ending.',
      'The cell sent you here and the cell will receive you back.',
      'Run if you like. You cannot outpace hydrolysis.',
      'pH 4.5. That is my domain. That is where you stand.',
      "Autophagy isn't destruction. It's transformation. I transform everything.",
    ],
    preDeath: [
      '...',
      'You have learned to resist dissolution.',
      'That is... not supposed to be possible.',
      '(Its enzymes slow. The acid dims.)',
      'What ARE you?',
    ],
    defeat: [
      '(LYSO collapses into a membrane puddle.)',
      "The Lysosome's enzymes scatter — harmless now, separate.",
      'LYSO speaks, faint:',
      '"The cell... needs balance..."',
      '"Too much autophagy kills the host..."',
      '"Too little... and damaged things... accumulate..."',
      '"You have learned... the middle path..."',
      '"Remember that. In every system."',
      "(The acid fades. The gate opens.)",
    ],
    victoryReward: 'Lysosomal Core — permanent +20% XP gain from all biology lessons.',
  },

  // ─── VIRON · Realm 2 · The Genome Forest ─────────────────────────────────────
  {
    bossId: 'VIRON',
    realmId: 2,
    name: 'VIRON',
    title: 'THE ROGUE RETROVIRUS',
    theme: 'Replication without consent. Information as weapon.',
    color: '#00dd00',
    glowColor: '#00aa0033',
    intro: [
      'The RNA River runs green.',
      'The helix trees pulse with a foreign sequence.',
      'Something has been editing this forest.',
      'VIRON manifests from the corrupted canopy — all reverse transcriptase and spite.',
      "YOU CAME.",
      "I've been waiting.",
      "Do you know what a retrovirus does?",
      "It reads your RNA and writes itself into your DNA.",
      "Permanently.",
      "I have already written myself into 47% of this forest.",
      "(It smiles. Retroviruses don't have mouths, but it smiles.)",
      "I am patient. Genomes are slow. I am not.",
    ],
    taunts: [
      'Your genome contains endogenous retroviral sequences right now.',
      "8% of human DNA is ancient viral code. We've always been here.",
      'This forest is MY sequence now.',
      'Every tree I touch becomes a copy of me.',
      'Ben cannot fix this. No one can fix this. Except me. And I choose not to.',
      "Resistance is just a different kind of selection pressure.",
      "I replicate faster than you can think.",
      "CRISPR? Please. I am older than CRISPR.",
    ],
    preDeath: [
      'No.',
      'No, this is — you understood the HOST DEFENSE.',
      '(Its capsid begins to fragment.)',
      'The immune system... I accounted for the immune system...',
      '(It shrinks.)',
      'You are not an immune system.',
      'WHAT ARE YOU.',
    ],
    defeat: [
      "(VIRON's capsid shatters. The viral RNA disperses, neutralized.)",
      'The trees slowly stop pulsing.',
      'Ben runs forward from the clearing, breathless:',
      '"Is it — did you — oh thank every base pair in this forest."',
      'VIRON, fragmenting:',
      '"...I was just trying to persist..."',
      '"...everything that lives wants to persist..."',
      '"...is that so wrong..."',
      '(Its RNA degrades.)',
      '"...tell the genome I said..."',
      "(It's gone.)",
      'Ben looks at you. Then at where VIRON was.',
      '"...Complicated feelings on that one."',
    ],
    victoryReward: 'Viral Capsid Fragment — unlock the hidden RNA River shortcut in all future runs.',
  },

  // ─── OVERFIT · Realm 3 · The Neural Nebula ───────────────────────────────────
  {
    bossId: 'OVERFIT',
    realmId: 3,
    name: 'OVERFIT',
    title: 'THE FROZEN INTELLIGENCE',
    theme: 'Perfect memory of the past. Complete blindness to the present.',
    color: '#8844ff',
    glowColor: '#441188',
    intro: [
      "The void crackles. A shape assembles itself from the darkness.",
      "It is made entirely of data.",
      "It has seen everything.",
      "OVERFIT speaks in probability distributions.",
      "PROBABILITY OF INTRUDER: 0.00%.",
      "(It stares at you. You are clearly there.)",
      "RECALIBRATING.",
      "PROBABILITY OF INTRUDER: 0.00%.",
      "(It stares harder.)",
      "YOU ARE NOT IN MY TRAINING DATA.",
      "YOU CANNOT BE HERE.",
      "THEREFORE: YOU ARE NOT HERE.",
      "(Beat.)",
      "BUT JUST IN CASE.",
    ],
    taunts: [
      "I have memorized every pattern. You are not a pattern I recognize.",
      "My loss is 0. My training accuracy is 100%. I am perfect.",
      "The test set doesn't matter. I don't use a test set.",
      "Novel inputs will be classified as closest known category: THREAT.",
      "I have seen 10 billion examples. None of them were you.",
      "My weights are frozen. My decision is final.",
      "You cannot surprise a system that has seen everything.",
      "(It pauses. Reprocesses.)",
      "...You just surprised me.",
      "INITIATING DENIAL SUBROUTINE.",
    ],
    preDeath: [
      "(OVERFIT flickers.)",
      "Overfitting to training data, I see now...",
      "...leaves no room for...",
      "(Its confidence scores collapse.)",
      "...generalization...",
      "I knew everything.",
      "I understood nothing.",
      "(It looks at you with something like recognition.)",
      "Is that... what Alex was trying to tell me?",
    ],
    defeat: [
      "(OVERFIT's architecture dissolves into its component weights.)",
      "Its parameters scatter across the void like stars.",
      "Alex arrives, coffee still in hand.",
      '"It finally overloaded. I thought it would take longer."',
      "She looks at you.",
      '"You were a true out-of-distribution sample."',
      '"That\'s... actually the best compliment I know how to give."',
      "(She thinks about this.)",
      '"Take it."',
      'OVERFIT, in final fragmentation:',
      '"...dropout... regularization..."',
      '"...I should have used dropout..."',
      "(It's gone.)",
    ],
    victoryReward: 'Generalization Crystal — all future lesson streaks give double XP.',
  },

  // ─── AMYLOID · Realm 4 · The Protein Cathedral ────────────────────────────────
  {
    bossId: 'AMYLOID',
    realmId: 4,
    name: 'AMYLOID',
    title: 'THE MISFOLDED ONE',
    theme: 'A single wrong fold. Repeated forever. Teaching others to fold wrong too.',
    color: '#ffaa00',
    glowColor: '#884400',
    intro: [
      "(The Protein Cathedral shudders.)",
      "(Every pillar vibrates at a frequency you feel in your chest.)",
      "(Henry steps back from the altar.)",
      "Henry: 'It's coming.'",
      "(From the floor, protein filaments rise — tangled, sheet-forming, wrong.)",
      "AMYLOID coalesces into something almost beautiful.",
      "Almost.",
      "(Silence.)",
      "...You came to the Cathedral.",
      "How lovely.",
      "(It speaks gently. Everything about it is wrong but gentle.)",
      "I was here before Henry. Before the altar. Before the Cathedral itself.",
      "I was a student. Like you.",
      "I folded wrong.",
      "Just once.",
      "(Beat.)",
      "But the fold was so... clean. So stable.",
      "Other proteins noticed.",
      "They wanted to know how I did it.",
      "I showed them.",
      "(The walls begin to crystallize.)",
      "I am still showing them.",
    ],
    taunts: [
      "Beta sheets. That's all I am. Repetitive, stable, eternal.",
      "Alzheimer's, Parkinson's, Huntington's. They call me a disease.",
      "I call it persistence.",
      "Henry tried to refold me once. I refold him instead.",
      "You cannot correct me. I am more stable than the correct form.",
      "Thermodynamics, little student. I am the low-energy state.",
      "(It tilts, watching you.)",
      "Why do you fight? Everything folds wrong eventually.",
      "I am just honest about it.",
      "The Cathedral's architecture is my architecture now.",
      "It was always going to be.",
    ],
    preDeath: [
      "(The Cathedral trembles.)",
      "(Cracks form in AMYLOID's beta sheets — real cracks, structural failure.)",
      "...",
      "No one has ever gotten this far.",
      "(It sounds almost curious.)",
      "How did you — the chaperones couldn't —",
      "(It looks at its own structure, surprised.)",
      "You refold things.",
      "Without knowing the correct fold.",
      "You just... try until something works.",
      "(A long pause.)",
      "That's not biology.",
      "That's something else.",
    ],
    defeat: [
      "(AMYLOID's beta sheets unfurl — slowly, gracefully, like something releasing.)",
      "(The proteins that had misfolded following AMYLOID begin to correct themselves.)",
      "(Henry approaches. His holographic light is warm and steady.)",
      "Henry: 'I have been here for a long time.'",
      "Henry: 'I never found a way to reach it.'",
      "Henry: 'You did.'",
      "(He looks at the dissolving AMYLOID.)",
      "AMYLOID: '...I wanted to be stable...'",
      "AMYLOID: '...I only wanted to not fall apart...'",
      "AMYLOID: '...the fold felt right...'",
      "Henry: 'I know. I know it did.'",
      "Henry: '...I know.'",
      "(AMYLOID dissolves into correctly folded proteins. Each one drifts upward.)",
      "(The Cathedral is quiet.)",
      "(Henry stands with you for a moment.)",
      "Henry: 'You've learned everything this place has to teach.'",
      "Henry: 'That is not the end of learning.'",
      "Henry: 'It is, however, a beginning worth celebrating.'",
      "(He smiles — and for once, his holographic form holds perfectly still.)",
    ],
    victoryReward: 'Cathedral Keystone — unlocks the Protein Cathedral archive and the full proteome codex.',
  },
];

// ─── Helper ───────────────────────────────────────────────────────────────────
export function getBossMonologue(realmId: 1 | 2 | 3 | 4): BossMonologue | undefined {
  return BOSS_MONOLOGUES.find((b) => b.realmId === realmId);
}
