// ─── Enemy Definitions — all 4 realms ────────────────────────────────────────

export interface Enemy {
  id: string;
  name: string;
  realmId: 1 | 2 | 3 | 4;
  hp: number;
  xpReward: number;
  gemReward: number;
  primaryColor: string;
  secondaryColor: string;
  size: 'small' | 'medium' | 'large';
  attackName: string;
  attackDescription: string;
  attackDamage: number;
  weaknessHint: string;
  lore: string;
  catchphrase: string;
  defeatQuip: string;
}

// ─── REALM 1: Cytoplasm ───────────────────────────────────────────────────────

const REALM1_ENEMIES: Enemy[] = [
  {
    id: 'r1-e1',
    name: 'Corrupted ATP Synthase',
    realmId: 1,
    hp: 30,
    xpReward: 50,
    gemReward: 6,
    primaryColor: '#8B1a00',
    secondaryColor: '#ffcc00',
    size: 'medium',
    attackName: 'Proton Backdraft',
    attackDescription: 'Reverses the proton gradient, draining ATP from the player and converting it to ADP.',
    attackDamage: 12,
    weaknessHint: 'Explain how chemiosmosis normally drives ATP production — restore the gradient direction.',
    lore: "ATP synthase should rotate clockwise, using the proton gradient to synthesize ATP. This one is spinning counterclockwise. It is consuming ATP and pumping protons the wrong way. Nobody told it. It does not know. This is somehow sadder.",
    catchphrase: 'WHRRRRR... BACKWARDS.',
    defeatQuip: "See, that's why membrane potential matters. Elliot said this quietly, for the 47th time.",
  },
  {
    id: 'r1-e2',
    name: 'Rogue mRNA Strand',
    realmId: 1,
    hp: 15,
    xpReward: 25,
    gemReward: 3,
    primaryColor: '#ff8800',
    secondaryColor: '#ffdd99',
    size: 'small',
    attackName: 'Mistranslation',
    attackDescription: 'Feeds the ribosome wrong codons, causing production of a nonsense protein that deals splash damage.',
    attackDamage: 8,
    weaknessHint: 'Identify the correct codon for the target amino acid — give the ribosome accurate instructions.',
    lore: "This mRNA was improperly spliced. An intron stayed in. The reading frame shifted at position 47. Everything downstream is wrong. The ribosome is doing its best with the information given. The mRNA is not doing its best. The mRNA is the problem.",
    catchphrase: 'CODON CODON STOP CODON — wait — CODON —',
    defeatQuip: 'Always check your splicing.',
  },
  {
    id: 'r1-e3',
    name: 'Lysosome Scout',
    realmId: 1,
    hp: 60,
    xpReward: 100,
    gemReward: 12,
    primaryColor: '#6600cc',
    secondaryColor: '#cc88ff',
    size: 'large',
    attackName: 'Hydrolysis',
    attackDescription: 'Releases hydrolytic enzymes that degrade the player\'s active proteins, reducing attack power.',
    attackDamage: 22,
    weaknessHint: 'Raise the pH — lysosomes operate at pH 4.5 and lose function as conditions become more neutral.',
    lore: "Lysosomes are not evil. They're the cell's recycling system — they digest damaged organelles, foreign invaders, worn proteins. They are incredibly useful. This one has decided that the definition of 'damaged' includes everything. It is not evil. It is enthusiastic.",
    catchphrase: 'DIGEST EVERYTHING. IT IS WHAT WE DO.',
    defeatQuip: "Lysosomes are not evil. They're just enthusiastic.",
  },
  {
    id: 'r1-e4',
    name: 'Unfolded Protein Blob',
    realmId: 1,
    hp: 20,
    xpReward: 35,
    gemReward: 4,
    primaryColor: '#888888',
    secondaryColor: '#cccccc',
    size: 'small',
    attackName: 'Aggregate',
    attackDescription: 'Recruits nearby unfolded proteins into a clump that deals increasing damage as it grows.',
    attackDamage: 7,
    weaknessHint: 'Deploy a chaperone protein — chaperones assist folding without becoming part of the final structure.',
    lore: "Protein folding is an extraordinarily complex problem. This protein has been trying to fold for six hours. The correct fold involves 347 amino acids arranged in a precise three-dimensional structure. It has achieved a lump. It is trying. It really is.",
    catchphrase: 'I... am... trying.',
    defeatQuip: "Protein folding is hard. Even in the real world it took 50 years to solve computationally. Cut it some slack.",
  },
  {
    id: 'r1-e5',
    name: 'Nuclease Specter',
    realmId: 1,
    hp: 40,
    xpReward: 65,
    gemReward: 8,
    primaryColor: '#003366',
    secondaryColor: '#88ccff',
    size: 'medium',
    attackName: 'DNA Cleavage',
    attackDescription: 'Cuts the player\'s active instructions at a random position, causing a turn of confused silence.',
    attackDamage: 15,
    weaknessHint: 'Name the restriction enzyme recognition sequence — specificity defeats indiscriminate cleavage.',
    lore: "Restriction enzymes are remarkable — they cleave DNA only at specific recognition sequences, protecting the cell from foreign DNA. This one lost its recognition sequence. It now cuts everything. Indiscriminately. With a small, satisfied sound.",
    catchphrase: '...snip.',
    defeatQuip: 'Specificity. This is why restriction enzymes have recognition sequences.',
  },
];

// ─── REALM 2: Genome Forest ───────────────────────────────────────────────────

const REALM2_ENEMIES: Enemy[] = [
  {
    id: 'r2-e1',
    name: 'Corrupted Read',
    realmId: 2,
    hp: 12,
    xpReward: 20,
    gemReward: 2,
    primaryColor: '#4488ff',
    secondaryColor: '#aaccff',
    size: 'small',
    attackName: 'Misalignment',
    attackDescription: 'Forces the player to accept an incorrect base call, shifting the reading frame.',
    attackDamage: 5,
    weaknessHint: 'Apply quality filtering — reads with Phred score below Q20 should be discarded.',
    lore: "Sequencing reads have quality scores. This one has a Q15 in a critical position. Q15 means roughly a 3% error rate at that base. 3% sounds small. In a genome of 3 billion bases, it is not small. Ben filters these. Always.",
    catchphrase: 'Q15 is FINE.',
    defeatQuip: 'Filter your reads. Always. — Ben, sighing.',
  },
  {
    id: 'r2-e2',
    name: 'Duplicate Chromosome',
    realmId: 2,
    hp: 35,
    xpReward: 55,
    gemReward: 7,
    primaryColor: '#ff4466',
    secondaryColor: '#ff99aa',
    size: 'medium',
    attackName: 'Copy Number Confusion',
    attackDescription: 'Creates a second copy of all current question options, making it impossible to identify the original.',
    attackDamage: 14,
    weaknessHint: 'Normalize read depth — copy number variants appear as changes in coverage relative to the reference.',
    lore: "Copy number variants — duplications and deletions of large genomic regions — account for more variation between humans than SNPs do. This pair of chromosomes cannot agree on which one existed first. Both are correct. Both are also very loud about it.",
    catchphrase: '"I WAS HERE FIRST." / "NO I WAS." / "I WAS." / "I WAS."',
    defeatQuip: 'Copy number variants account for more variation than SNPs. — Ben, eating a sandwich.',
  },
  {
    id: 'r2-e3',
    name: 'Misannotated Gene',
    realmId: 2,
    hp: 18,
    xpReward: 30,
    gemReward: 4,
    primaryColor: '#ff9900',
    secondaryColor: '#ffddaa',
    size: 'small',
    attackName: 'Wrong Annotation',
    attackDescription: 'Labels all answer options with incorrect function descriptions, requiring deduction from first principles.',
    attackDamage: 8,
    weaknessHint: 'Check the primary sequence and run homology search — function follows from sequence, not annotation.',
    lore: "Someone annotated this gene as 'hypothetical protein' in 1998 and the annotation propagated to eleven databases. Three papers cited it. All three cited the same wrong annotation. The gene has an actual function. Nobody checked. The annotation is still there.",
    catchphrase: 'I AM HYPOTHETICAL. I HAVE ALWAYS BEEN HYPOTHETICAL.',
    defeatQuip: "Someone annotated this wrong in 1998. It's still wrong. Check your sources.",
  },
  {
    id: 'r2-e4',
    name: 'Tandem Repeat Monster',
    realmId: 2,
    hp: 55,
    xpReward: 90,
    gemReward: 11,
    primaryColor: '#aa00ff',
    secondaryColor: '#ddaaff',
    size: 'large',
    attackName: 'Repeat Expansion',
    attackDescription: 'Adds an additional copy of the current question with each failed attempt, compounding difficulty.',
    attackDamage: 20,
    weaknessHint: 'Identify the repeat unit and count — the pathogenic threshold for CAG repeats is above 36 copies.',
    lore: "Trinucleotide repeat expansion is responsible for Huntington's disease, fragile X syndrome, myotonic dystrophy. The more times the sequence repeats, the worse the phenotype. This entity has been adding copies since it arrived. It is now very large. Ben notes that it is 'technically doing what tandem repeats do, just faster.'",
    catchphrase: 'CAGCAGCAGCAGCAGCAGCAGCAGCAG —',
    defeatQuip: "Trinucleotide repeat expansion. Some diseases exist to make bioinformaticians' lives interesting.",
  },
];

// ─── REALM 3: Neural Nebula ───────────────────────────────────────────────────

const REALM3_ENEMIES: Enemy[] = [
  {
    id: 'r3-e1',
    name: 'Overfitted Minion',
    realmId: 3,
    hp: 20,
    xpReward: 35,
    gemReward: 4,
    primaryColor: '#00cc44',
    secondaryColor: '#99ffcc',
    size: 'small',
    attackName: 'Memorization',
    attackDescription: 'Forces the player to answer an exact question from training data — fails if the phrasing changes at all.',
    attackDamage: 9,
    weaknessHint: 'Apply dropout — disabling random units forces generalization over memorization.',
    lore: "This minion has a training accuracy of 100%. It knows every training example by heart. It will tell you the answer to any training question instantly. Ask it a new question and it stares at you. The answer is 7. The answer is always 7. Even when the question is about protein folding.",
    catchphrase: 'I ALREADY KNOW THE ANSWER. THE ANSWER IS 7.',
    defeatQuip: 'Generalization is the point. Not memorization.',
  },
  {
    id: 'r3-e2',
    name: 'Vanishing Gradient',
    realmId: 3,
    hp: 30,
    xpReward: 50,
    gemReward: 6,
    primaryColor: '#334455',
    secondaryColor: '#667788',
    size: 'medium',
    attackName: 'Gradient Fade',
    attackDescription: 'Reduces the XP reward of the current question by a multiplier that decreases each turn.',
    attackDamage: 11,
    weaknessHint: 'Use ReLU activation and batch normalization — gradients survive deeper networks with proper architecture.',
    lore: "In deep neural networks, gradients can become exponentially small as they propagate back through layers. Early layers stop learning. The network only updates its final layers. This entity embodies that — it started with a full gradient signal and is now almost imperceptibly faint. It is still trying to communicate.",
    catchphrase: '...help.',
    defeatQuip: 'ReLU. That is why ReLU exists.',
  },
  {
    id: 'r3-e3',
    name: 'NaN Entity',
    realmId: 3,
    hp: 5,
    xpReward: 200,
    gemReward: 25,
    primaryColor: '#ff0000',
    secondaryColor: '#000000',
    size: 'small',
    attackName: 'Loss Explosion',
    attackDescription: 'Instantly sets the player\'s current score to NaN. Must be defeated before the lesson can continue.',
    attackDamage: 999,
    weaknessHint: 'Clip gradients and reduce learning rate — NaN loss is almost always caused by exploding gradients or a bad lr.',
    lore: "NaN: Not a Number. When a loss function computes an undefined value — division by zero, log of a negative, gradient explosion — the loss becomes NaN and training halts. This entity is that moment. It has 5 HP. It is terrifying anyway. Alex has a personal history with it.",
    catchphrase: '...',
    defeatQuip: 'I have a personal relationship with this entity. — Alex, haunted.',
  },
  {
    id: 'r3-e4',
    name: 'Attention Head Hydra',
    realmId: 3,
    hp: 70,
    xpReward: 120,
    gemReward: 14,
    primaryColor: '#ff6600',
    secondaryColor: '#ffcc66',
    size: 'large',
    attackName: 'Quadratic Complexity',
    attackDescription: 'For each additional question answered, this enemy gains 2 additional heads and attacks increase.',
    attackDamage: 18,
    weaknessHint: 'Apply sparse attention — limit attention to a fixed window to reduce computational overhead.',
    lore: "Multi-head attention allows a transformer to attend to different representation subspaces simultaneously. Eight heads is standard. Sixteen is ambitious. This entity has been adding heads. It now has forty-seven. Each one is computing query-key-value products simultaneously. The quadratic complexity is, Alex says, 'starting to become a concern.'",
    catchphrase: 'QUERY. KEY. VALUE. QUERY. KEY. VALUE. QUERY —',
    defeatQuip: 'Multi-head attention is good. This one just has too many heads.',
  },
  {
    id: 'r3-e5',
    name: 'Learning Rate Demon',
    realmId: 3,
    hp: 45,
    xpReward: 75,
    gemReward: 9,
    primaryColor: '#cc0088',
    secondaryColor: '#ff88dd',
    size: 'medium',
    attackName: 'Overshoot',
    attackDescription: 'Alternates between dealing massive damage and zero damage, making timing unpredictable.',
    attackDamage: 17,
    weaknessHint: 'Apply a cosine annealing schedule — warm up the learning rate, then decay it smoothly.',
    lore: "A learning rate too high overshoots the minimum — the loss oscillates and never converges. A learning rate too low crawls and may get stuck in local minima. This entity cannot decide which it is. It oscillates between enormous and microscopic. It has been doing this for 200 epochs. The loss curve looks like a seismograph.",
    catchphrase: 'TOO FAST — wait — TOO SLOW — NO FASTER — WAIT —',
    defeatQuip: 'Use a scheduler. Please.',
  },
];

// ─── REALM 4: Protein Cathedral ───────────────────────────────────────────────

const REALM4_ENEMIES: Enemy[] = [
  {
    id: 'r4-e1',
    name: 'Amyloid Fibril Soldier',
    realmId: 4,
    hp: 25,
    xpReward: 40,
    gemReward: 5,
    primaryColor: '#888899',
    secondaryColor: '#ccccdd',
    size: 'small',
    attackName: 'Aggregate Recruitment',
    attackDescription: 'Recruits the next enemy to join the battle prematurely, creating a 2v1 encounter.',
    attackDamage: 10,
    weaknessHint: 'Identify the amyloidogenic sequence motif — proteins with high beta-sheet propensity are most vulnerable.',
    lore: "Amyloid fibrils are extraordinarily stable — hydrogen-bonded beta-sheet stacks that resist degradation. One misfolded seed is sufficient to template the misfolding of correctly folded neighbors. Aggregation propagates. This soldier is both a victim and a vector. It does not distinguish between them.",
    catchphrase: 'Join us.',
    defeatQuip: 'Aggregation propagates. One seed is enough. This is why early intervention matters.',
  },
  {
    id: 'r4-e2',
    name: 'Disulfide Bond Bandit',
    realmId: 4,
    hp: 40,
    xpReward: 65,
    gemReward: 8,
    primaryColor: '#ccaa00',
    secondaryColor: '#ffee88',
    size: 'medium',
    attackName: 'Wrong Cross-Link',
    attackDescription: 'Forms an incorrect covalent bond between two of the player\'s answer options, fusing them.',
    attackDamage: 15,
    weaknessHint: 'Apply reducing agent — dithiothreitol (DTT) breaks disulfide bonds and allows refolding.',
    lore: "Disulfide bonds between cysteine residues are crucial for protein stability and function. They form in the oxidizing environment of the ER. They are also irreversible under normal conditions. This bandit has formed wrong disulfide bonds — cysteines that should not be linked, linked. The protein is stuck in the wrong shape. Permanently, unless you do something about it.",
    catchphrase: 'CROSS-LINKED. IRREVOCABLY.',
    defeatQuip: 'Disulfide bonds are crucial. Also irreversible in the wrong conditions.',
  },
  {
    id: 'r4-e3',
    name: 'Phantom Crystal',
    realmId: 4,
    hp: 10,
    xpReward: 15,
    gemReward: 2,
    primaryColor: '#aaddff',
    secondaryColor: '#ffffff',
    size: 'small',
    attackName: 'Diffraction Noise',
    attackDescription: 'Adds crystallographic noise to the question display, making text harder to read.',
    attackDamage: 4,
    weaknessHint: 'Improve crystal quality — better resolution requires fewer mosaic defects and larger crystal size.',
    lore: "X-ray crystallography requires a perfect crystal — ordered, large enough to diffract, correctly cryo-protected. A perfect crystal takes months to grow. These fragments are not perfect crystals. They are 0.05 mm shards with high mosaicity. They appear in groups and scatter X-rays into noise. One perfect crystal is worth a thousand fragments.",
    catchphrase: 'hssssss.',
    defeatQuip: 'One perfect crystal is worth a thousand fragments.',
  },
  {
    id: 'r4-e4',
    name: 'Prediction Ghost',
    realmId: 4,
    hp: 35,
    xpReward: 60,
    gemReward: 7,
    primaryColor: '#88aacc',
    secondaryColor: '#ddeeff',
    size: 'medium',
    attackName: 'Uncertainty',
    attackDescription: 'Makes the correct answer translucent and hard to select while boosting wrong answers\' visibility.',
    attackDamage: 13,
    weaknessHint: 'Check the pLDDT score — AlphaFold marks intrinsically disordered regions with low confidence scores.',
    lore: "Intrinsically disordered proteins do not adopt a fixed three-dimensional structure. They are flexible by design — disorder enables binding to multiple partners, post-translational modification, regulatory functions. This entity has confused 'intrinsically disordered' with 'choosing not to be structured.' There is a difference. Henry notes it gently.",
    catchphrase: 'I COULD be structured. I CHOOSE not to be.',
    defeatQuip: 'Intrinsically disordered proteins are real and important. Just harder to work with.',
  },
  {
    id: 'r4-e5',
    name: 'Amyloid Tyrant',
    realmId: 4,
    hp: 200,
    xpReward: 500,
    gemReward: 50,
    primaryColor: '#222233',
    secondaryColor: '#8888cc',
    size: 'large',
    attackName: 'Total Aggregation',
    attackDescription: 'Pulls all active enemies into an amyloid cascade — damage compounds each round until dissolved.',
    attackDamage: 35,
    weaknessHint: 'Identify the fibril core sequence and apply structure-based drug design — the Amyloid Tyrant has a specific vulnerable conformation.',
    lore: "The Amyloid Tyrant was once a correctly folded protein. It met an alternative conformation. The alternative conformation was certain. The Amyloid Tyrant was uncertain. It chose certainty. It has been recruiting others since. Every misfolded fibril in the cathedral traces back to this single seeding event, decades ago.",
    catchphrase: 'CERTAINTY. STABILITY. PERMANENCE. COME.',
    defeatQuip: "The amyloid is dissolving. Henry exhales for the first time in what feels like years.",
  },
];

// ─── REALM_ENEMIES Record ─────────────────────────────────────────────────────

export const REALM_ENEMIES: Record<1 | 2 | 3 | 4, Enemy[]> = {
  1: REALM1_ENEMIES,
  2: REALM2_ENEMIES,
  3: REALM3_ENEMIES,
  4: REALM4_ENEMIES,
};

export const ALL_ENEMIES: Enemy[] = [
  ...REALM1_ENEMIES,
  ...REALM2_ENEMIES,
  ...REALM3_ENEMIES,
  ...REALM4_ENEMIES,
];

export function getEnemyById(id: string): Enemy | undefined {
  return ALL_ENEMIES.find((e) => e.id === id);
}

export function getEnemiesByRealm(realmId: 1 | 2 | 3 | 4): Enemy[] {
  return REALM_ENEMIES[realmId];
}
