// ─── BitBio — Complete RPG Narrative ─────────────────────────────────────────
// Full story across all 4 realms + intro + epilogue. 36 story beats total.

export interface StoryBeat {
  id: string;
  realm: 0 | 1 | 2 | 3 | 4;   // 0 = pre-realm intro / void
  trigger: 'enter-realm' | 'node-complete' | 'boss-defeated' | 'item-pickup' | 'npc-talk' | 'game-start';
  nodeId?: string;
  speaker: 'Elliot' | 'Ben' | 'Alex' | 'Henry' | 'Enzyme' | 'NARRATOR' | 'LYSO' | 'VIRON' | 'OVERFIT' | 'AMYLOID';
  lines: string[];
  portrait?: string;
  mood?: 'normal' | 'excited' | 'worried' | 'dark' | 'triumphant' | 'mysterious';
}

// ─── INTRO: The Void ─────────────────────────────────────────────────────────

const INTRO_BEATS: StoryBeat[] = [
  {
    id: 'intro-0',
    realm: 0,
    trigger: 'game-start',
    speaker: 'NARRATOR',
    mood: 'mysterious',
    lines: [
      'This is the Void.',
      'It is not nothing. Nothing is too simple for what this is.',
      'This is the space between understanding.',
      'You have been here a while.',
      'You did not notice.',
    ],
  },
  {
    id: 'intro-1',
    realm: 0,
    trigger: 'game-start',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'excited',
    lines: [
      'Oh FINALLY.',
      "I've been sitting here for three days.",
      "Do you know how long three days is when you're a cat? It's forever. It's an eternity of staring at a wall.",
      "(She stretches, tail curling.)",
      "I'm Enzyme. I'll be accompanying you.",
      "Non-negotiable. I've already decided.",
      "(Beat.)",
      "Don't you want to ask why a cat is in the void?",
      "(You don't.)",
      "Smart. It's a long answer and also I don't fully know.",
    ],
  },
  {
    id: 'intro-2',
    realm: 0,
    trigger: 'game-start',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'excited',
    lines: [
      "Anyway. Biology.",
      "You're about to learn an enormous amount of it.",
      "Four realms. Four mentors. Approximately one cat's worth of moral support.",
      "Also there are bosses. I'll be honest with you.",
      "Actually —",
      "(She looks at a portal that has opened behind you.)",
      "— I'll explain on the way.",
      "Go through the portal.",
      "(Beat.)",
      "I said GO THROUGH THE PORTAL.",
      "(She headbutts you through it.)",
    ],
  },
];

// ─── REALM 1: The Cytoplasm ───────────────────────────────────────────────────

const REALM1_BEATS: StoryBeat[] = [
  {
    id: 'r1-enter',
    realm: 1,
    trigger: 'enter-realm',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'excited',
    lines: [
      "We're inside a cell.",
      "I know.",
      "(She looks around at the towering organelles.)",
      "No — I KNOW. It's a lot.",
      "The tall guy in the lab coat over there is named Elliot. He's been here for three weeks.",
      "He has opinions about ribosomes. Many opinions.",
      "Try not to encourage him.",
      "(Beat.)",
      "Just kidding. He's great. Also the cell is in crisis.",
      "I'll let him explain. He's been rehearsing.",
    ],
  },
  {
    id: 'r1-node1-complete',
    realm: 1,
    trigger: 'node-complete',
    nodeId: 'l1-m1-n1',
    speaker: 'Elliot',
    portrait: 'elliot',
    mood: 'excited',
    lines: [
      "You — you actually understood that.",
      "The ribosomes responded to you.",
      "Three WEEKS I've been in here and they just made nonsense proteins for me.",
      "You walk in here for twenty minutes and suddenly they're doing the right thing.",
      "(He looks at his notes from three weeks of failed communication attempts.)",
      "(He very slowly puts the notes in his pocket.)",
      "...This is fine. I'm fine.",
    ],
  },
  {
    id: 'r1-node2-complete',
    realm: 1,
    trigger: 'node-complete',
    nodeId: 'l1-m2-n1',
    speaker: 'Elliot',
    portrait: 'elliot',
    mood: 'worried',
    lines: [
      "The ER is stabilizing. Good.",
      "But LYSO is moving again.",
      "I can see it on the sensors — four organelles to the east.",
      "(He pulls out a very crumpled map.)",
      "It ate my fluorescence microscope last Tuesday.",
      "It was a very good microscope.",
      "(Quietly:)",
      "The microscope did not deserve that.",
    ],
  },
  {
    id: 'r1-enzyme-mid',
    realm: 1,
    trigger: 'node-complete',
    nodeId: 'l1-m2-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'normal',
    lines: [
      "You're doing really well.",
      "(She says this while washing her face, which is a very cat thing to do mid-crisis.)",
      "Also I figured out why LYSO went rogue.",
      "There's a corrupted gene on chromosome 4. Bad instructions. LYSO is just following them.",
      "It's not evil. It's just... obedient to something broken.",
      "(Beat.)",
      "That's almost sadder.",
      "Anyway. Keep going.",
    ],
  },
  {
    id: 'r1-node3-complete',
    realm: 1,
    trigger: 'node-complete',
    nodeId: 'l1-m3-n1',
    speaker: 'Elliot',
    portrait: 'elliot',
    mood: 'dark',
    lines: [
      "The Nucleus is talking to us.",
      "(This is new.)",
      "It says the instruction error originated in a damaged promoter region on chromosome 4.",
      "Someone modified the TFEB binding site three weeks ago.",
      "LYSO thinks it's doing exactly what it's supposed to do.",
      "(He goes very quiet.)",
      "It's been trying to do the right thing.",
      "This whole time.",
      "I need to sit down.",
    ],
  },
  {
    id: 'r1-boss-warning',
    realm: 1,
    trigger: 'node-complete',
    nodeId: 'l1-m3-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'worried',
    lines: [
      "LYSO is ahead.",
      "(She presses close to your leg.)",
      "I don't get scared. I'm a cat. Cats are not scared of things.",
      "(She is very clearly a little scared.)",
      "What you're about to face isn't a villain. It's a protein following bad instructions.",
      "That means you can't just fight it. You have to correct it.",
      "Show it what the right instruction looks like.",
      "(Long pause.)",
      "I believe in you. Also please don't let it dissolve me.",
    ],
  },
  {
    id: 'r1-boss-defeated',
    realm: 1,
    trigger: 'boss-defeated',
    speaker: 'Elliot',
    portrait: 'elliot',
    mood: 'triumphant',
    lines: [
      "The lysosome is retreating.",
      "The corrupted gene is repaired — the Nucleus pushed a corrected mRNA.",
      "LYSO is just... being a lysosome again.",
      "Quietly. Correctly. The way it was supposed to.",
      "(He watches the organelles begin to move normally.)",
      "The mitochondria are unpacking.",
      "The Golgi is regrowing its stacks.",
      "(He covers his face for a moment.)",
      "(Then, muffled:)",
      "Thank you. I really, genuinely, mean that.",
      "(Longer pause.)",
      "Please don't tell anyone it took you three hours and it took me three weeks.",
    ],
  },
  {
    id: 'r1-transition',
    realm: 1,
    trigger: 'boss-defeated',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'excited',
    lines: [
      "The Genome Forest portal just opened.",
      "(She is already walking toward it.)",
      "There's a kid there. Ben. He's sixteen and knows more about genomics than most professors.",
      "He's very chill about it. Aggressively chill.",
      "Also there's a retrovirus that's been rewriting the forest for two hundred years.",
      "(Beat.)",
      "After you.",
    ],
  },
];

// ─── REALM 2: The Genome Forest ───────────────────────────────────────────────

const REALM2_BEATS: StoryBeat[] = [
  {
    id: 'r2-enter',
    realm: 2,
    trigger: 'enter-realm',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'normal',
    lines: [
      "(She sniffs the air.)",
      "It smells like wet DNA in here.",
      "That's the chromosomal trees. They're sequences, literally — ATCG spiraling up the bark.",
      "(She looks at one.)",
      "That one says ATGG where it should say ATCG.",
      "One letter. One nucleotide.",
      "That's the difference between functional and broken.",
      "(She looks at you.)",
      "Ben's around here somewhere. He's the one eating a sandwich on a log.",
    ],
  },
  {
    id: 'r2-node1-complete',
    realm: 2,
    trigger: 'node-complete',
    nodeId: 'l2-m1-n1',
    speaker: 'Ben',
    portrait: 'ben',
    mood: 'normal',
    lines: [
      "(He does not look up from his paper.)",
      "Good.",
      "(He finishes his sandwich.)",
      "The reference genome is partially restored at locus 14q31.",
      "The trees in that sector are regrowing correctly.",
      "(He opens another paper.)",
      "You're fast. That took me a week when I first got here.",
      "(Beat.)",
      "I was also eating a lot of sandwiches that week. Possible correlation.",
    ],
  },
  {
    id: 'r2-node2-complete',
    realm: 2,
    trigger: 'node-complete',
    nodeId: 'l2-m2-n1',
    speaker: 'Ben',
    portrait: 'ben',
    mood: 'worried',
    lines: [
      "(He looks up. This is rare.)",
      "I ran BLAST on the new variants.",
      "98.7% identity match with a retroviral insert. Specifically an endogenous retrovirus.",
      "ERV — most of them are harmless. Ancient. Inactive.",
      "This one isn't.",
      "(He closes his laptop.)",
      "Something reactivated it. Three months ago, based on the spread rate.",
      "We need to find where it integrated first.",
    ],
  },
  {
    id: 'r2-enzyme-mid',
    realm: 2,
    trigger: 'node-complete',
    nodeId: 'l2-m2-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'normal',
    lines: [
      "I found the original integration site.",
      "(She drops a piece of bark at your feet.)",
      "Ancient tree. North sector. The sequence there reads like it's been there for two hundred years.",
      "VIRON didn't invade recently. It's been here the whole time.",
      "Dormant. Waiting.",
      "(Beat.)",
      "Something woke it up.",
      "(She does not say what. She looks away.)",
    ],
  },
  {
    id: 'r2-node3-complete',
    realm: 2,
    trigger: 'node-complete',
    nodeId: 'l2-m3-n1',
    speaker: 'Ben',
    portrait: 'ben',
    mood: 'dark',
    lines: [
      "Found VIRON's integration signature.",
      "It's been using reverse transcriptase to copy itself into every new tree that grows.",
      "Standard retroviral strategy.",
      "(He writes something in his notebook.)",
      "The thing is... it's good at it.",
      "From a purely technical standpoint — the efficiency of integration is remarkable.",
      "(He closes the notebook.)",
      "I don't admire it. I'm just observing.",
      "Now let's remove it.",
    ],
  },
  {
    id: 'r2-boss-warning',
    realm: 2,
    trigger: 'node-complete',
    nodeId: 'l2-m3-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'worried',
    lines: [
      "VIRON is ahead.",
      "It knows you're coming.",
      "Retroviruses are actually... kind of brilliant, mechanistically. They're just misapplied.",
      "Convert RNA to DNA, integrate into the host genome, use the host's own machinery.",
      "It's using the forest's own replication to spread.",
      "(She looks at you seriously.)",
      "You'll need to think like a CRISPR guide — find the target, cut precisely, don't disturb the rest.",
      "You can do that.",
    ],
  },
  {
    id: 'r2-boss-defeated',
    realm: 2,
    trigger: 'boss-defeated',
    speaker: 'Ben',
    portrait: 'ben',
    mood: 'triumphant',
    lines: [
      "(He is already on his laptop.)",
      "Reference genome restored at 99.2% accuracy.",
      "VIRON sequences silenced via methylation — it's still there, technically, but it can't express.",
      "That's how we handle endogenous retroviruses in real cells too, actually.",
      "(He looks up for a full three seconds.)",
      "You did good.",
      "(He opens a new paper.)",
      "I'm sixteen.",
      "(Beat.)",
      "I just want that on record.",
    ],
  },
  {
    id: 'r2-transition',
    realm: 2,
    trigger: 'boss-defeated',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'excited',
    lines: [
      "Neural Nebula is next.",
      "Alex is there. She's intense. She's on her sixth coffee.",
      "She's also one of the best machine learning researchers alive, so.",
      "(She starts walking.)",
      "There's a network there that's achieved perfect training accuracy.",
      "Which sounds good until I tell you it fails on everything else.",
      "It's sentient now. It's been memorizing instead of learning.",
      "(She looks back at you.)",
      "Sounds familiar? No? Just a thought.",
    ],
  },
];

// ─── REALM 3: The Neural Nebula ───────────────────────────────────────────────

const REALM3_BEATS: StoryBeat[] = [
  {
    id: 'r3-enter',
    realm: 3,
    trigger: 'enter-realm',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'normal',
    lines: [
      "(She stares at the floating loss curves above.)",
      "One of those graphs is at zero.",
      "That one. The one labeled OVERFIT.",
      "That's the problem.",
      "Zero training loss means it memorized every training example.",
      "Every noise artifact. Every mistake in the dataset.",
      "It doesn't know anything. It just remembers everything.",
      "(Beat.)",
      "Alex is over there. Don't mention epoch 3 unless you want her to stare into the middle distance for a long time.",
    ],
  },
  {
    id: 'r3-node1-complete',
    realm: 3,
    trigger: 'node-complete',
    nodeId: 'l3-m1-n1',
    speaker: 'Alex',
    portrait: 'alex',
    mood: 'excited',
    lines: [
      "(She saves a checkpoint without looking up.)",
      "It's learning.",
      "Not OVERFIT — this new network. The one you just trained.",
      "(She pulls up two curves side by side: training loss and validation loss.)",
      "They're both going down. Together.",
      "That's what it's supposed to look like.",
      "OVERFIT's training loss has been at zero for nineteen days.",
      "Its validation loss is... I can't look at it.",
      "(She looks at it.)",
      "Yeah. Yeah that's bad.",
    ],
  },
  {
    id: 'r3-enzyme-mid',
    realm: 3,
    trigger: 'node-complete',
    nodeId: 'l3-m2-n1',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'worried',
    lines: [
      "OVERFIT is expanding.",
      "(She is watching something far off — a massive glowing network, much larger than it was.)",
      "It's absorbing smaller networks. Showing them its weights.",
      "Convincing them it has the answers.",
      "(Beat.)",
      "The smaller networks believe it.",
      "OVERFIT has 100% confidence in every prediction.",
      "Confidence is very compelling when you're a new model that doesn't know what it doesn't know.",
      "(She turns to you.)",
      "Sound familiar now?",
    ],
  },
  {
    id: 'r3-node2-complete',
    realm: 3,
    trigger: 'node-complete',
    nodeId: 'l3-m2-n2',
    speaker: 'Alex',
    portrait: 'alex',
    mood: 'dark',
    lines: [
      "I've been thinking about this.",
      "OVERFIT didn't set out to be wrong.",
      "It optimized exactly as trained. Gradient descent worked perfectly.",
      "The problem is what it was optimizing for.",
      "Training accuracy. Not generalization.",
      "(She closes her laptop.)",
      "It's not malicious. It's doing exactly what the objective function told it to do.",
      "We gave it the wrong objective.",
      "(Long pause.)",
      "The objective matters more than the optimizer.",
      "Remember that.",
    ],
  },
  {
    id: 'r3-node3-complete',
    realm: 3,
    trigger: 'node-complete',
    nodeId: 'l3-m3-n1',
    speaker: 'Alex',
    portrait: 'alex',
    mood: 'worried',
    lines: [
      "(She pulls up a confusion matrix.)",
      "OVERFIT's test set performance.",
      "It has 99.9% confidence on every prediction.",
      "(She turns the matrix to face you.)",
      "It's wrong 94% of the time.",
      "But it never doubts itself.",
      "That's the terrifying part — not the wrongness, but the certainty.",
      "(Quietly:)",
      "I had a colleague like that once.",
      "We don't talk about it.",
    ],
  },
  {
    id: 'r3-boss-warning',
    realm: 3,
    trigger: 'node-complete',
    nodeId: 'l3-m3-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'dark',
    lines: [
      "OVERFIT knows you're coming.",
      "It's already predicted this encounter.",
      "(Beat.)",
      "It predicted you'd fail.",
      "With 99.9% confidence.",
      "(She looks at you.)",
      "The thing about a model that's never seen out-of-distribution data is that it can't handle it.",
      "You are out-of-distribution.",
      "You are generalization.",
      "Be something it hasn't memorized.",
    ],
  },
  {
    id: 'r3-boss-defeated',
    realm: 3,
    trigger: 'boss-defeated',
    speaker: 'Alex',
    portrait: 'alex',
    mood: 'triumphant',
    lines: [
      "(She watches the validation loss curve for a long time.)",
      "It's dropping.",
      "Not OVERFIT — OVERFIT is gone. Regularized out of existence.",
      "The other networks. The ones it absorbed.",
      "They're generalizing again.",
      "(She opens a new training run.)",
      "Loss diverging to the right. Not too fast. Learning rate is good.",
      "Validation following training.",
      "(A pause.)",
      "(Quietly:)",
      "This is the first time I've felt okay since epoch 3.",
    ],
  },
  {
    id: 'r3-transition',
    realm: 3,
    trigger: 'boss-defeated',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'mysterious',
    lines: [
      "Last realm.",
      "(She says this quietly, which is unusual for her.)",
      "The Protein Cathedral.",
      "Henry is there. He's been there... a long time.",
      "(She pauses.)",
      "There's something I should tell you about Henry.",
      "(Long pause.)",
      "(She doesn't tell you.)",
      "You'll understand when you get there.",
      "Come on.",
    ],
  },
];

// ─── REALM 4: The Protein Cathedral ──────────────────────────────────────────

const REALM4_BEATS: StoryBeat[] = [
  {
    id: 'r4-enter',
    realm: 4,
    trigger: 'enter-realm',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'mysterious',
    lines: [
      "(She walks slowly. No running. No jokes.)",
      "Henry built this cathedral from scratch.",
      "Every pillar is a correctly folded alpha helix. Every arch is a beta sheet.",
      "It took him forty years.",
      "(She pauses at the entrance.)",
      "He was a person once. A real person.",
      "Professor Henry Lacks. Structural biologist.",
      "He discovered the first evidence of amyloid cascades in 1973.",
      "Nobody believed him.",
      "(Quietly:)",
      "He's been waiting for someone to prove he was right.",
      "I think that's you.",
    ],
  },
  {
    id: 'r4-node1-complete',
    realm: 4,
    trigger: 'node-complete',
    nodeId: 'l4-m1-n1',
    speaker: 'Henry',
    portrait: 'henry',
    mood: 'mysterious',
    lines: [
      "(He is quiet for a moment after you complete the lesson.)",
      "AlphaFold changed everything.",
      "For fifty years, humanity attempted to predict protein structure from sequence alone.",
      "In 2020, a neural network solved it.",
      "(He looks at his hands — translucent, flickering.)",
      "I wrote a paper in 1974 predicting it would eventually be solved with machine learning.",
      "I sent it to six journals.",
      "Four rejected it outright.",
      "One lost it.",
      "One published a letter saying my methodology was 'speculative to the point of irresponsibility.'",
      "(Beat.)",
      "I find that less upsetting than I used to.",
    ],
  },
  {
    id: 'r4-node2-complete',
    realm: 4,
    trigger: 'node-complete',
    nodeId: 'l4-m2-n1',
    speaker: 'Henry',
    portrait: 'henry',
    mood: 'dark',
    lines: [
      "(He leads you into the amyloid section. Everything gray.)",
      "Amyloid.",
      "A correctly folded protein, encountering a misfolded one.",
      "Being recruited.",
      "Adopting the wrong conformation.",
      "Then recruiting another.",
      "A cascade.",
      "(He stops in front of a large gray mass.)",
      "This is what Alzheimer's looks like at the molecular level.",
      "Parkinson's. Prion disease. Type 2 diabetes.",
      "(Long pause.)",
      "My wife was a cell biologist. She had a theory about HeLa cells.",
      "She was right about that too.",
      "(He touches the gray mass and pulls his hand back.)",
      "Let's continue.",
    ],
  },
  {
    id: 'r4-enzyme-reveal',
    realm: 4,
    trigger: 'node-complete',
    nodeId: 'l4-m2-n2',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'mysterious',
    lines: [
      "(She is sitting very still.)",
      "Henry's wife.",
      "(Long pause.)",
      "Her cells are still alive. In labs, in hospitals, in research facilities.",
      "Henrietta Lacks. 1951.",
      "The most reproduced human cells in history.",
      "HeLa cells.",
      "Henry found a way to preserve himself in the digital realm to keep studying them.",
      "(She looks at you.)",
      "He's been here for fifty years.",
      "He never got credit for the amyloid discovery.",
      "He's been waiting for someone to understand it.",
      "(Beat.)",
      "That's you.",
      "Please don't mess this up.",
    ],
  },
  {
    id: 'r4-node3-complete',
    realm: 4,
    trigger: 'node-complete',
    nodeId: 'l4-m3-n1',
    speaker: 'Henry',
    portrait: 'henry',
    mood: 'dark',
    lines: [
      "(He pulls up an AlphaFold confidence map of the Amyloid Tyrant.)",
      "The misfolded core — pLDDT score near zero.",
      "The structure is completely uncertain.",
      "But it has tremendous inertia.",
      "Other proteins fold toward it because — perversely — the wrong fold has more structural persistence.",
      "(He closes the map.)",
      "Certainty is not correctness.",
      "I tried to publish that in 1975.",
      "The same journal called it 'metaphysically confused.'",
      "(He almost smiles.)",
      "They were not wrong about that part.",
      "Come. The Amyloid Tyrant is ahead.",
    ],
  },
  {
    id: 'r4-boss-warning',
    realm: 4,
    trigger: 'node-complete',
    nodeId: 'l4-m3-n2',
    speaker: 'Henry',
    portrait: 'henry',
    mood: 'worried',
    lines: [
      "Before you face it.",
      "(He turns to face you fully.)",
      "The Amyloid Tyrant is not evil.",
      "It is protein. Following physics.",
      "Doing exactly what thermodynamics tells it to do.",
      "The problem is not what it is.",
      "The problem is what it's displacing.",
      "(Beat.)",
      "There's something else.",
      "If you dissolve it — if the misfolded fibrils dissociate —",
      "(His projection flickers more intensely.)",
      "I believe I can come back.",
      "Not as a hologram.",
      "As myself.",
      "(Quietly:)",
      "I've been waiting quite a long time.",
    ],
  },
  {
    id: 'r4-boss-defeated',
    realm: 4,
    trigger: 'boss-defeated',
    speaker: 'NARRATOR',
    mood: 'triumphant',
    lines: [
      'The amyloid fibrils dissociate.',
      'The misfolded proteins unfold, then refold correctly.',
      'The cathedral heals — gray sections flush with color.',
      'Alpha helices reform. Beta sheets untwist.',
      'Light refracts through properly structured protein again.',
      'And then:',
      'Henry Lacks stops flickering.',
    ],
  },
  {
    id: 'r4-henry-restored',
    realm: 4,
    trigger: 'boss-defeated',
    speaker: 'Henry',
    portrait: 'henry',
    mood: 'triumphant',
    lines: [
      "(He looks at his hands. They are not translucent.)",
      "(He looks at you. He is fully, solidly there.)",
      "...",
      "(A very long pause.)",
      "(Then, quietly:)",
      "Oh.",
      "(He laughs — not holographic, not calculated. Just a laugh.)",
      "Oh.",
      "I can sneeze now.",
      "(He sneezes.)",
      "(He laughs again.)",
      "I've been trying to sneeze for fifty years.",
      "Thank you.",
      "(A beat.)",
      "You understood protein structure.",
      "And in doing so —",
      "You proved I was right.",
      "(He finally says the word he's been waiting fifty years to say:)",
      "Published.",
    ],
  },
  {
    id: 'r4-enzyme-end',
    realm: 4,
    trigger: 'boss-defeated',
    speaker: 'Enzyme',
    portrait: 'enzyme',
    mood: 'triumphant',
    lines: [
      "(She is sitting on Henry's shoulder. He seems surprised but accepts it.)",
      "You did it.",
      "All four realms.",
      "Cell biology. Genomics. Machine learning. Structural biology.",
      "(She looks at you with an expression that is, somehow, proud.)",
      "I knew you could do it.",
      "(Beat.)",
      "I also knew because I can see the future.",
      "I'm a cat.",
      "We can all do that.",
      "(Henry gently removes her from his shoulder. She immediately climbs back.)",
      "Go get your certificate.",
      "You've earned it.",
    ],
  },
];

// ─── EPILOGUE ─────────────────────────────────────────────────────────────────

export const EPILOGUE_LETTERS: Record<string, string[]> = {
  elliot: [
    "Dear graduate,",
    "You've learned everything I know about cell biology. Which is a lot. I counted: it's a lot.",
    "The cell is back to normal. The ribosomes are making correct proteins. The Golgi has all seven stacks again.",
    "LYSO is just being a lysosome. Correctly. The way it was always trying to.",
    "I got a promotion, technically, because 'eliminated cellular crisis' is a very strong line item.",
    "I also got a microscope. A better one than the one LYSO ate.",
    "Thank you for coming. The cytoplasm was better with you in it.",
    "Scientifically yours,",
    "Elliot",
    "P.S. — Mitochondria: powerhouse of the cell. I need you to know I will say this forever.",
  ],
  ben: [
    "Hey.",
    "The paper is published.",
    "67 citations in the first month.",
    "I'm 16.",
    "Just so you know.",
    "You were good at this. The genomics stuff. Really good.",
    "Also you're the only person I've ever met who didn't ask me to explain BLAST immediately.",
    "Respect.",
    "The genome forest is clean. The retrovirus is silenced.",
    "The trees are growing right again.",
    "Take care of yourself. Eat a sandwich occasionally.",
    "Ben",
    "(I have published 3 more papers since you left. Productivity is up.)",
    "(The sandwiches help.)",
  ],
  alex: [
    "Validation loss: 0.031.",
    "That's the final model's score. The one you helped generalize.",
    "It's been running on the competition dataset for two weeks. It's generalizing correctly.",
    "OVERFIT is gone. The nebula has space again.",
    "Coffee count since you left: 14. That's lower than before you arrived.",
    "I believe you had a stabilizing effect on the training environment.",
    "Or I'm sleeping more. Unclear.",
    "You understood gradient descent. And overfitting. And transformers.",
    "You understood all of it.",
    "That matters.",
    "—Alex",
    "P.S. I looked up the startup that pivoted to pretzels. They're doing well.",
    "P.P.S. The pretzels are very good.",
  ],
  henry: [
    "To my student,",
    "In 1973, I submitted a paper describing amyloid cascade dynamics.",
    "The journal said: 'The hypothesis, while original, lacks sufficient mechanistic grounding.'",
    "In 1975, I submitted a revised version.",
    "The same journal said: 'We have no record of the original submission.'",
    "In 2024, I watched you dissolve the Amyloid Tyrant by understanding exactly the mechanism I described.",
    "The mechanism I was told did not exist.",
    "So.",
    "...",
    "I sneezed this morning. On purpose. Just to do it.",
    "You gave me that.",
    "You gave me time to say: I was right, and now someone knows it.",
    "Thank you.",
    "—Professor Henry Lacks",
    "P.S. — Enzyme has decided to stay here.",
    "P.P.S. — I don't mind.",
    "P.P.P.S. — I sneezed again. Twice. Both times: intentional.",
  ],
  enzyme: [
    "I knew you could do it.",
    "I also knew because I can see the future.",
    "I'm a cat.",
    "We can all do that.",
    "Also: good job.",
    "Also: I'm going to stay with Henry for a while.",
    "He needed someone to sneeze on. Figuratively.",
    "(Literally. He won't stop sneezing.)",
    "You'll be okay.",
    "You have the certificate.",
    "You have the biology.",
    "You have everything.",
    "(A paw print at the bottom of the page.)",
    "—Enzyme",
    "(P.S. — Mitochondria: powerhouse of the cell.)",
    "(Elliot taught me that. I'm not sorry either.)",
  ],
};

// ─── Master Export ─────────────────────────────────────────────────────────────

export const FULL_STORY: StoryBeat[] = [
  ...INTRO_BEATS,
  ...REALM1_BEATS,
  ...REALM2_BEATS,
  ...REALM3_BEATS,
  ...REALM4_BEATS,
];

export function getStoryBeats(realm: 0 | 1 | 2 | 3 | 4): StoryBeat[] {
  return FULL_STORY.filter((b) => b.realm === realm);
}

export function getBeatByTrigger(realm: 0 | 1 | 2 | 3 | 4, trigger: StoryBeat['trigger'], nodeId?: string): StoryBeat | undefined {
  return FULL_STORY.find(
    (b) => b.realm === realm && b.trigger === trigger && (nodeId ? b.nodeId === nodeId : true)
  );
}
